<?php

namespace Database\Seeders;

use App\Models\Active;
use Illuminate\Database\Seeder;

class ActionSeeder extends Seeder
{
    public function run(): void
    {
        $actions =
        [
            ['ticker' => 'AMER3', 'name' => 'Americanas', 'price' => '0.33', 'type' => 'actions'],
            ['ticker' => 'RENT3', 'name' => 'Localiza', 'price' => '40', 'type' => 'actions'],
            ['ticker' => 'HAPV3', 'name' => 'Hapvida', 'price' => '4.41', 'type' => 'actions'],
            ['ticker' => 'COGN3', 'name' => 'Cogna', 'price' => '1.39', 'type' => 'actions'],
            ['ticker' => 'ITUB4', 'name' => 'Itaú Unibanco', 'price' => '36.47', 'type' => 'actions'],
            ['ticker' => 'BBDC4', 'name' => 'Banco Bradesco', 'price' => '15.01', 'type' => 'actions'],
            ['ticker' => 'VALE3', 'name' => 'Vale', 'price' => '56', 'type' => 'actions'],
            ['ticker' => 'IFCM3', 'name' => 'Infracommerce', 'price' => '0.29', 'type' => 'actions'],
            ['ticker' => 'B3SA3', 'name' => 'B3', 'price' => '12.7', 'type' => 'actions'],
            ['ticker' => 'PETR4', 'name' => 'Petrobras', 'price' => '37.76', 'type' => 'actions'],
            ['ticker' => 'AZUL4', 'name' => 'Azul', 'price' => '7.75', 'type' => 'actions'],
            ['ticker' => 'ITSA4', 'name' => 'Itaúsa', 'price' => '10.86', 'type' => 'actions'],
            ['ticker' => 'CIEL3', 'name' => 'Cielo', 'price' => '5.81', 'type' => 'actions'],
            ['ticker' => 'RAIZ4', 'name' => 'Raízen', 'price' => '3.25', 'type' => 'actions'],
            ['ticker' => 'CMIG4', 'name' => 'CEMIG', 'price' => '11.97', 'type' => 'actions'],
            ['ticker' => 'MGLU3', 'name' => 'Magazine Luiza', 'price' => '12.74', 'type' => 'actions'],
            ['ticker' => 'MLAS3', 'name' => 'Multilaser', 'price' => '1.83', 'type' => 'actions'],
            ['ticker' => 'JBSS3', 'name' => 'JBS', 'price' => '37.34', 'type' => 'actions'],
            ['ticker' => 'ABEV3', 'name' => 'Ambev', 'price' => '12.56', 'type' => 'actions'],
            ['ticker' => 'RDOR3', 'name' => ""		 , 'price' => '30.73', 'type' => 'actions'],
            ['ticker' => 'BBAS3', 'name' => 'Banco do Brasil', 'price' => '27.93', 'type' => 'actions'],
            ['ticker' => 'ENEV3', 'name' => 'Eneva', 'price' => '13.47', 'type' => 'actions'],
            ['ticker' => 'LREN3', 'name' => 'Lojas Renner', 'price' => '16.19', 'type' => 'actions'],
            ['ticker' => 'MRVE3', 'name' => 'MRV', 'price' => '7.28', 'type' => 'actions'],
            ['ticker' => 'CMIN3', 'name' => 'CSN Mineração', 'price' => '5', 'type' => 'actions'],
            ['ticker' => 'LWSA3', 'name' => 'Locaweb', 'price' => '4.77', 'type' => 'actions'],
            ['ticker' => 'CPLE6', 'name' => 'Copel', 'price' => '10.53', 'type' => 'actions'],
            ['ticker' => 'NTCO3', 'name' => 'Natura', 'price' => '14.75', 'type' => 'actions'],
            ['ticker' => 'ONCO3', 'name' => 'Oncoclínicas', 'price' => '6.3', 'type' => 'actions'],
            ['ticker' => 'USIM5', 'name' => 'Usiminas', 'price' => '06.09', 'type' => 'actions'],
            ['ticker' => 'RAIL3', 'name' => 'Rumo', 'price' => '23.38', 'type' => 'actions'],
            ['ticker' => 'PCAR3', 'name' => 'Grupo Pão de Açúcar', 'price' => '3.2', 'type' => 'actions'],
            ['ticker' => 'CVCB3', 'name' => 'CVC', 'price' => '1.91', 'type' => 'actions'],
            ['ticker' => 'BRFS3', 'name' => 'BRF', 'price' => '23.51', 'type' => 'actions'],
            ['ticker' => 'ASAI3', 'name' => 'Assaí', 'price' => '10.67', 'type' => 'actions'],
            ['ticker' => 'RADL3', 'name' => 'RaiaDrogasil', 'price' => '30', 'type' => 'actions'],
            ['ticker' => 'BEEF3', 'name' => 'Minerva', 'price' => '7.59', 'type' => 'actions'],
            ['ticker' => 'PETR3', 'name' => 'Petrobras', 'price' => '40.98', 'type' => 'actions'],
            ['ticker' => 'ANIM3', 'name' => 'Ânima Educação', 'price' => '3.27', 'type' => 'actions'],
            ['ticker' => 'GGBR4', 'name' => 'Gerdau', 'price' => '17.4', 'type' => 'actions'],
            ['ticker' => 'CSAN3', 'name' => 'Cosan', 'price' => '13.51', 'type' => 'actions'],
            ['ticker' => 'PETZ3', 'name' => 'Petz', 'price' => '3.82', 'type' => 'actions'],
            ['ticker' => 'CSNA3', 'name' => 'Siderúrgica Nacional', 'price' => '11.7', 'type' => 'actions'],
            ['ticker' => 'PRIO3', 'name' => 'PetroRio', 'price' => '49.6', 'type' => 'actions'],
            ['ticker' => 'EQTL3', 'name' => 'Equatorial Energia', 'price' => '35.46', 'type' => 'actions'],
            ['ticker' => 'TIMS3', 'name' => 'TIM', 'price' => '18.1', 'type' => 'actions'],
            ['ticker' => 'ALPA4', 'name' => 'Alpargatas', 'price' => '7.86', 'type' => 'actions'],
            ['ticker' => 'BBDC3', 'name' => 'Banco Bradesco', 'price' => '13.39', 'type' => 'actions'],
            ['ticker' => 'WEGE3', 'name' => 'WEG', 'price' => '51.54', 'type' => 'actions'],
            ['ticker' => 'MRFG3', 'name' => 'Marfrig', 'price' => '12.83', 'type' => 'actions'],
            ['ticker' => 'VVEO3', 'name' => 'Viveo', 'price' => '2.28', 'type' => 'actions'],
            ['ticker' => 'VAMO3', 'name' => 'Grupo Vamos', 'price' => '8.32', 'type' => 'actions'],
            ['ticker' => 'POMO4', 'name' => 'Marcopolo', 'price' => '6.94', 'type' => 'actions'],
            ['ticker' => 'MOVI3', 'name' => 'Movida', 'price' => '7.37', 'type' => 'actions'],
            ['ticker' => 'GOAU4', 'name' => 'Metalúrgica Gerdau', 'price' => '10.09', 'type' => 'actions'],
            ['ticker' => 'VBBR3', 'name' => 'Vibra Energia', 'price' => '25.24', 'type' => 'actions'],
            ['ticker' => 'ELET3', 'name' => 'Eletrobras', 'price' => '40.15', 'type' => 'actions'],
            ['ticker' => 'SUZB3', 'name' => 'Suzano', 'price' => '54.7', 'type' => 'actions'],
            ['ticker' => 'ALOS3', 'name' => 'Allos', 'price' => '23.65', 'type' => 'actions'],
            ['ticker' => 'LJQQ3', 'name' => 'Lojas Quero-Quero', 'price' => '4.27', 'type' => 'actions'],
            ['ticker' => 'CRFB3', 'name' => 'Carrefour Brasil', 'price' => '9.77', 'type' => 'actions'],
            ['ticker' => 'STBP3', 'name' => 'Santos Brasil', 'price' => '14.1', 'type' => 'actions'],
            ['ticker' => 'RRRP3', 'name' => '3R Petroleum', 'price' => '29.58', 'type' => 'actions'],
            ['ticker' => 'UGPA3', 'name' => 'Ultrapar', 'price' => '23.6', 'type' => 'actions'],
            ['ticker' => 'EMBR3', 'name' => 'Embraer', 'price' => '43.94', 'type' => 'actions'],
            ['ticker' => 'MULT3', 'name' => 'Multiplan', 'price' => '27.31', 'type' => 'actions'],
            ['ticker' => 'BBSE3', 'name' => 'BB Seguridade', 'price' => '37.45', 'type' => 'actions'],
            ['ticker' => 'AURE3', 'name' => 'Auren Energia', 'price' => '11.64', 'type' => 'actions'],
            ['ticker' => 'VIVA3', 'name' => 'Vivara', 'price' => '27.1', 'type' => 'actions'],
            ['ticker' => 'BHIA3', 'name' => 'Casas Bahia', 'price' => '5.1', 'type' => 'actions'],
            ['ticker' => 'CCRO3', 'name' => 'Grupo CCR', 'price' => '13.52', 'type' => 'actions'],
            ['ticker' => 'CPLE3', 'name' => 'Copel', 'price' => '9.53', 'type' => 'actions'],
            ['ticker' => 'JFEN3', 'name' => 'João Fortes', 'price' => '0.25', 'type' => 'actions'],
            ['ticker' => 'SEQL3', 'name' => 'Sequoia Logística', 'price' => '6.1', 'type' => 'actions'],
            ['ticker' => 'TRPL4', 'name' => 'Transmissão Paulista', 'price' => '24.71', 'type' => 'actions'],
            ['ticker' => 'SBSP3', 'name' => 'Sabesp', 'price' => '99.46', 'type' => 'actions'],
            ['ticker' => 'HYPE3', 'name' => 'Hypera', 'price' => '31.65', 'type' => 'actions'],
            ['ticker' => 'YDUQ3', 'name' => 'YDUQS', 'price' => '10.02', 'type' => 'actions'],
            ['ticker' => 'CLSA3', 'name' => 'ClearSale', 'price' => '6.95', 'type' => 'actions'],
            ['ticker' => 'AZEV4', 'name' => 'Azevedo & Travassos', 'price' => '1.4', 'type' => 'actions'],
            ['ticker' => 'GFSA3', 'name' => 'Gafisa', 'price' => '2.88', 'type' => 'actions'],
            ['ticker' => 'SMFT3', 'name' => 'Smart Fit', 'price' => '23.35', 'type' => 'actions'],
            ['ticker' => 'SIMH3', 'name' => 'Simpar', 'price' => '6.54', 'type' => 'actions'],
            ['ticker' => 'PDGR3', 'name' => 'PDG Realty', 'price' => '0.19', 'type' => 'actions'],
            ['ticker' => 'TEND3', 'name' => 'Construtora Tenda', 'price' => '13.19', 'type' => 'actions'],
            ['ticker' => 'FLRY3', 'name' => 'Fleury', 'price' => '15.59', 'type' => 'actions'],
            ['ticker' => 'BRAP4', 'name' => 'Bradespar', 'price' => '18.06', 'type' => 'actions'],
            ['ticker' => 'CYRE3', 'name' => 'Cyrela', 'price' => '21.63', 'type' => 'actions'],
            ['ticker' => 'TOTS3', 'name' => 'Totvs', 'price' => '29.66', 'type' => 'actions'],
            ['ticker' => 'CBAV3', 'name' => 'CBA', 'price' => '4.62', 'type' => 'actions'],
            ['ticker' => 'SRNA3', 'name' => 'Serena Energia', 'price' => '09.04', 'type' => 'actions'],
            ['ticker' => 'JHSF3', 'name' => 'JHSF', 'price' => '4.22', 'type' => 'actions'],
            ['ticker' => 'ENJU3', 'name' => 'Enjoei', 'price' => '1.8', 'type' => 'actions'],
            ['ticker' => 'SLCE3', 'name' => 'SLC Agrícola', 'price' => '18.2', 'type' => 'actions'],
            ['ticker' => 'CEAB3', 'name' => 'C&A', 'price' => '8.84', 'type' => 'actions'],
            ['ticker' => 'HBSA3', 'name' => 'Hidrovias do Brasil', 'price' => '3.7', 'type' => 'actions'],
            ['ticker' => 'GOLL4', 'name' => 'GOL', 'price' => '1.15', 'type' => 'actions'],
            ['ticker' => 'BRSR6', 'name' => 'Banrisul', 'price' => '12.36', 'type' => 'actions'],
            ['ticker' => 'POSI3', 'name' => 'Positivo', 'price' => '7.18', 'type' => 'actions'],
            ['ticker' => 'VIVT3', 'name' => 'Vivo', 'price' => '51.62', 'type' => 'actions'],
            ['ticker' => 'ECOR3', 'name' => 'EcoRodovias', 'price' => '7.82', 'type' => 'actions'],
            ['ticker' => 'AZZA3', 'name' => 'Arezzo', 'price' => '55.16', 'type' => 'actions'],
            ['ticker' => 'BRKM5', 'name' => 'Braskem', 'price' => '16.55', 'type' => 'actions'],
            ['ticker' => 'QUAL3', 'name' => 'Qualicorp', 'price' => '1.58', 'type' => 'actions'],
            ['ticker' => 'AESB3', 'name' => 'AES Brasil', 'price' => '11.4', 'type' => 'actions'],
            ['ticker' => 'GMAT3', 'name' => 'Grupo Mateus', 'price' => '08.06', 'type' => 'actions'],
            ['ticker' => 'RECV3', 'name' => 'PetroRecôncavo', 'price' => '21.8', 'type' => 'actions'],
            ['ticker' => 'DXCO3', 'name' => 'Dexco', 'price' => '7.65', 'type' => 'actions'],
            ['ticker' => 'RAPT4', 'name' => 'Randon', 'price' => '11.06', 'type' => 'actions'],
            ['ticker' => 'TTEN3', 'name' => '3tentos', 'price' => '11.56', 'type' => 'actions'],
            ['ticker' => 'CXSE3', 'name' => 'Caixa Seguridade', 'price' => '14.41', 'type' => 'actions'],
            ['ticker' => 'PSSA3', 'name' => 'Porto Seguro', 'price' => '32.86', 'type' => 'actions'],
            ['ticker' => 'IRBR3', 'name' => 'IRB Brasil RE', 'price' => '32.52', 'type' => 'actions'],
            ['ticker' => 'ELET6', 'name' => 'Eletrobras', 'price' => '44.64', 'type' => 'actions'],
            ['ticker' => 'CPFE3', 'name' => 'CPFL Energia', 'price' => '33.77', 'type' => 'actions'],
            ['ticker' => 'KLBN4', 'name' => 'Klabin', 'price' => '4.18', 'type' => 'actions'],
            ['ticker' => 'BPAN4', 'name' => 'Banco Pan', 'price' => '9.76', 'type' => 'actions'],
            ['ticker' => 'SMTO3', 'name' => 'São Martinho', 'price' => '29.88', 'type' => 'actions'],
            ['ticker' => 'EZTC3', 'name' => 'EZTEC', 'price' => '13.97', 'type' => 'actions'],
            ['ticker' => 'ABCB4', 'name' => 'Banco ABC Brasil', 'price' => '22.69', 'type' => 'actions'],
            ['ticker' => 'ZAMP3', 'name' => 'Zamp', 'price' => '3.31', 'type' => 'actions'],
            ['ticker' => 'SBFG3', 'name' => 'Grupo SBF', 'price' => '16.68', 'type' => 'actions'],
            ['ticker' => 'HBOR3', 'name' => 'Helbor', 'price' => '2.17', 'type' => 'actions'],
            ['ticker' => 'EGIE3', 'name' => 'Engie', 'price' => '46.32', 'type' => 'actions'],
            ['ticker' => 'AMBP3', 'name' => 'Ambipar', 'price' => '69.95', 'type' => 'actions'],
            ['ticker' => 'DIRR3', 'name' => 'Direcional', 'price' => '28.99', 'type' => 'actions'],
            ['ticker' => 'TRIS3', 'name' => 'Trisul', 'price' => '4.71', 'type' => 'actions'],
            ['ticker' => 'CASH3', 'name' => 'Méliuz', 'price' => '6.4', 'type' => 'actions'],
            ['ticker' => 'GUAR3', 'name' => 'Guararapes', 'price' => '8.79', 'type' => 'actions'],
            ['ticker' => 'GGPS3', 'name' => 'GPS', 'price' => '17.85', 'type' => 'actions'],
            ['ticker' => 'MILS3', 'name' => 'Mills', 'price' => '11.7', 'type' => 'actions'],
            ['ticker' => 'ODPV3', 'name' => 'Odontoprev', 'price' => '11.66', 'type' => 'actions'],
            ['ticker' => 'TUPY3', 'name' => 'Tupy', 'price' => '26.9', 'type' => 'actions'],
            ['ticker' => 'SAPR4', 'name' => 'Sanepar', 'price' => '5.8', 'type' => 'actions'],
            ['ticker' => 'MEAL3', 'name' => 'IMC Alimentação', 'price' => '1.65', 'type' => 'actions'],
            ['ticker' => 'CSMG3', 'name' => 'COPASA', 'price' => '23.2', 'type' => 'actions'],
            ['ticker' => 'LIGT3', 'name' => 'Light', 'price' => '4.85', 'type' => 'actions'],
            ['ticker' => 'MATD3', 'name' => 'Mater Dei', 'price' => '4.44', 'type' => 'actions'],
            ['ticker' => 'CURY3', 'name' => 'Cury', 'price' => '23.63', 'type' => 'actions'],
            ['ticker' => 'DASA3', 'name' => 'Dasa', 'price' => '2.8', 'type' => 'actions'],
            ['ticker' => 'NEOE3', 'name' => 'Neoenergia', 'price' => '19.38', 'type' => 'actions'],
            ['ticker' => 'CAML3', 'name' => 'Camil Alimentos', 'price' => '9.99', 'type' => 'actions'],
            ['ticker' => 'OPCT3', 'name' => 'OceanPact', 'price' => '6.55', 'type' => 'actions'],
            ['ticker' => 'ETER3', 'name' => 'Eternit', 'price' => '06.06', 'type' => 'actions'],
            ['ticker' => 'RANI3', 'name' => 'Irani', 'price' => '08.08', 'type' => 'actions'],
            ['ticker' => 'PRNR3', 'name' => 'Priner', 'price' => '11.91', 'type' => 'actions'],
            ['ticker' => 'EVEN3', 'name' => 'Even', 'price' => '6.47', 'type' => 'actions'],
            ['ticker' => 'AERI3', 'name' => 'Aeris Energy', 'price' => '8.81', 'type' => 'actions'],
            ['ticker' => 'CSED3', 'name' => 'Cruzeiro do Sul Educacional', 'price' => '3.94', 'type' => 'actions'],
            ['ticker' => 'INTB3', 'name' => 'Intelbras', 'price' => '21.77', 'type' => 'actions'],
            ['ticker' => 'GRND3', 'name' => 'Grendene', 'price' => '6.24', 'type' => 'actions'],
            ['ticker' => 'LAVV3', 'name' => 'Lavvi Incorporadora', 'price' => '8.83', 'type' => 'actions'],
            ['ticker' => 'MDIA3', 'name' => 'M. Dias Branco', 'price' => '28.95', 'type' => 'actions'],
            ['ticker' => 'PLPL3', 'name' => 'Plano&Plano', 'price' => '12.2', 'type' => 'actions'],
            ['ticker' => 'SOJA3', 'name' => 'Boa Safra Sementes', 'price' => '13.87', 'type' => 'actions'],
            ['ticker' => 'BMGB4', 'name' => 'Banco BMG', 'price' => '3.65', 'type' => 'actions'],
            ['ticker' => 'FESA4', 'name' => 'Ferbasa', 'price' => '08.08', 'type' => 'actions'],
            ['ticker' => 'VLID3', 'name' => 'Valid', 'price' => '20.83', 'type' => 'actions'],
            ['ticker' => 'KRSA3', 'name' => 'Kora Saúde', 'price' => '0.6', 'type' => 'actions'],
            ['ticker' => 'JALL3', 'name' => 'Jalles Machado', 'price' => '6.79', 'type' => 'actions'],
            ['ticker' => 'MTRE3', 'name' => 'Mitre Realty', 'price' => '3.9', 'type' => 'actions'],
            ['ticker' => 'KEPL3', 'name' => 'Kepler Weber', 'price' => '11.41', 'type' => 'actions'],
            ['ticker' => 'AZEV3', 'name' => 'Azevedo & Travassos', 'price' => '1.41', 'type' => 'actions'],
            ['ticker' => 'MYPK3', 'name' => 'Iochpe-Maxion', 'price' => '11.51', 'type' => 'actions'],
            ['ticker' => 'SEER3', 'name' => 'Ser Educacional', 'price' => '5.51', 'type' => 'actions'],
            ['ticker' => 'LOGG3', 'name' => 'LOG CP', 'price' => '24.12', 'type' => 'actions'],
            ['ticker' => 'PNVL3', 'name' => 'Dimed', 'price' => '10.91', 'type' => 'actions'],
            ['ticker' => 'VULC3', 'name' => 'Vulcabras', 'price' => '17.87', 'type' => 'actions'],
            ['ticker' => 'SHOW3', 'name' => 'Time For Fun', 'price' => '1.29', 'type' => 'actions'],
            ['ticker' => 'BRIT3', 'name' => 'Brisanet', 'price' => '3.94', 'type' => 'actions'],
            ['ticker' => 'AMAR3', 'name' => 'Lojas Marisa', 'price' => '1.3', 'type' => 'actions'],
            ['ticker' => 'ITUB3', 'name' => 'Itaú Unibanco', 'price' => '31.31', 'type' => 'actions'],
            ['ticker' => 'TASA4', 'name' => 'Taurus', 'price' => '11.01', 'type' => 'actions'],
            ['ticker' => 'VITT3', 'name' => 'Vittia', 'price' => '5.99', 'type' => 'actions'],
            ['ticker' => 'MDNE3', 'name' => 'Moura Dubeux', 'price' => '14.64', 'type' => 'actions'],
            ['ticker' => 'CMIG3', 'name' => 'CEMIG', 'price' => '13.79', 'type' => 'actions'],
            ['ticker' => 'TECN3', 'name' => 'Technos', 'price' => '5.88', 'type' => 'actions'],
            ['ticker' => 'PINE4', 'name' => 'Banco Pine', 'price' => '4.67', 'type' => 'actions'],
            ['ticker' => 'ARML3', 'name' => 'Armac', 'price' => '09.02', 'type' => 'actions'],
            ['ticker' => 'MELK3', 'name' => 'Melnick', 'price' => '3.6', 'type' => 'actions'],
            ['ticker' => 'NGRD3', 'name' => 'Neogrid', 'price' => '1.21', 'type' => 'actions'],
            ['ticker' => 'USIM3', 'name' => 'Usiminas', 'price' => '5.94', 'type' => 'actions'],
            ['ticker' => 'PGMN3', 'name' => 'Pague Menos', 'price' => '2.94', 'type' => 'actions'],
            ['ticker' => 'TGMA3', 'name' => 'Tegma', 'price' => '25.56', 'type' => 'actions'],
            ['ticker' => 'MBLY3', 'name' => 'Mobly', 'price' => '2.76', 'type' => 'actions'],
            ['ticker' => 'PTBL3', 'name' => 'Portobello', 'price' => '4.68', 'type' => 'actions'],
            ['ticker' => 'WIZC3', 'name' => 'Wiz Soluções', 'price' => '6', 'type' => 'actions'],
            ['ticker' => 'JSLG3', 'name' => 'JSL', 'price' => '9.25', 'type' => 'actions'],
            ['ticker' => 'KLBN3', 'name' => 'Klabin', 'price' => '4.2', 'type' => 'actions'],
            ['ticker' => 'ESPA3', 'name' => 'Espaçolaser', 'price' => '01.02', 'type' => 'actions'],
            ['ticker' => 'TFCO4', 'name' => 'Track & Field', 'price' => '12.25', 'type' => 'actions'],
            ['ticker' => 'ORVR3', 'name' => 'Orizon', 'price' => '46.17', 'type' => 'actions'],
            ['ticker' => 'FRAS3', 'name' => 'Fras-le', 'price' => '18.48', 'type' => 'actions'],
            ['ticker' => 'LEVE3', 'name' => 'Mahle Metal Leve', 'price' => '33.69', 'type' => 'actions'],
            ['ticker' => 'TAEE4', 'name' => 'Taesa', 'price' => '11.85', 'type' => 'actions'],
            ['ticker' => 'SHUL4', 'name' => 'Schulz', 'price' => '6.54', 'type' => 'actions'],
            ['ticker' => 'HBRE3', 'name' => 'HBR Realty', 'price' => '5.2', 'type' => 'actions'],
            ['ticker' => 'FIQE3', 'name' => 'Unifique', 'price' => '3.79', 'type' => 'actions'],
            ['ticker' => 'OIBR3', 'name' => 'Oi', 'price' => '4.3', 'type' => 'actions'],
            ['ticker' => 'PORT3', 'name' => 'Wilson Sons', 'price' => '16.72', 'type' => 'actions'],
            ['ticker' => 'BMOB3', 'name' => 'Bemobi', 'price' => '16.1', 'type' => 'actions'],
            ['ticker' => 'UNIP6', 'name' => 'Unipar', 'price' => '49.06', 'type' => 'actions'],
            ['ticker' => 'SAPR3', 'name' => 'Sanepar', 'price' => '5.42', 'type' => 'actions'],
            ['ticker' => 'AGXY3', 'name' => 'AgroGalaxy', 'price' => '1.48', 'type' => 'actions'],
            ['ticker' => 'AGRO3', 'name' => 'BrasilAgro', 'price' => '26.35', 'type' => 'actions'],
            ['ticker' => 'RNEW4', 'name' => 'Renova Energia', 'price' => '0.89', 'type' => 'actions'],
            ['ticker' => 'RCSL4', 'name' => 'Recrusul', 'price' => '0.85', 'type' => 'actions'],
            ['ticker' => 'ITSA3', 'name' => 'Itaúsa', 'price' => '10.82', 'type' => 'actions'],
            ['ticker' => 'POMO3', 'name' => 'Marcopolo', 'price' => '5.48', 'type' => 'actions'],
            ['ticker' => 'ELMD3', 'name' => 'Eletromidia', 'price' => '18.8', 'type' => 'actions'],
            ['ticker' => 'LPSB3', 'name' => 'Lopes', 'price' => '1.78', 'type' => 'actions'],
            ['ticker' => 'SANB3', 'name' => 'Banco Santander', 'price' => '14.12', 'type' => 'actions'],
            ['ticker' => 'SANB4', 'name' => 'Banco Santander', 'price' => '15.85', 'type' => 'actions'],
            ['ticker' => 'DESK3', 'name' => 'Desktop', 'price' => '16.35', 'type' => 'actions'],
            ['ticker' => 'BLAU3', 'name' => 'Blau Farmacêutica', 'price' => '11.93', 'type' => 'actions'],
            ['ticker' => 'RCSL3', 'name' => 'Recrusul', 'price' => '2.91', 'type' => 'actions'],
            ['ticker' => 'PFRM3', 'name' => 'Profarma', 'price' => '5.77', 'type' => 'actions'],
            ['ticker' => 'ROMI3', 'name' => 'Indústrias ROMI', 'price' => '10.9', 'type' => 'actions'],
            ['ticker' => 'TAEE3', 'name' => 'Taesa', 'price' => '11.76', 'type' => 'actions'],
            ['ticker' => 'BRAP3', 'name' => 'Bradespar', 'price' => '17.57', 'type' => 'actions'],
            ['ticker' => 'GOAU3', 'name' => 'Metalúrgica Gerdau', 'price' => '10.25', 'type' => 'actions'],
            ['ticker' => 'DEXP3', 'name' => 'Dexxos', 'price' => '9.65', 'type' => 'actions'],
            ['ticker' => 'VTRU3', 'name' => 'VITRUBREPCOM', 'price' => '10.99', 'type' => 'actions'],
            ['ticker' => 'TCSA3', 'name' => 'Tecnisa', 'price' => '02.06', 'type' => 'actions'],
            ['ticker' => 'BIOM3', 'name' => 'Biomm', 'price' => '8.69', 'type' => 'actions'],
            ['ticker' => 'CSUD3', 'name' => 'CSU Cardsystem', 'price' => '18.85', 'type' => 'actions'],
            ['ticker' => 'PMAM3', 'name' => 'Paranapanema', 'price' => '02.06', 'type' => 'actions'],
            ['ticker' => 'GGBR3', 'name' => 'Gerdau', 'price' => '15.48', 'type' => 'actions'],
            ['ticker' => 'INEP3', 'name' => 'Inepar', 'price' => '1.93', 'type' => 'actions'],
            ['ticker' => 'ALPK3', 'name' => 'Estapar', 'price' => '3.94', 'type' => 'actions'],
            ['ticker' => 'DEXP4', 'name' => 'Dexxos', 'price' => '9.19', 'type' => 'actions'],
            ['ticker' => 'LUPA3', 'name' => 'Lupatech', 'price' => '1.63', 'type' => 'actions'],
            ['ticker' => 'TPIS3', 'name' => 'Triunfo', 'price' => '4.3', 'type' => 'actions'],
            ['ticker' => 'TRAD3', 'name' => 'Traders Club', 'price' => '3.7', 'type' => 'actions'],
            ['ticker' => 'VIVR3', 'name' => 'Viver', 'price' => '2.53', 'type' => 'actions'],
            ['ticker' => 'CTSA4', 'name' => 'Santanense', 'price' => '1.35', 'type' => 'actions'],
            ['ticker' => 'SYNE3', 'name' => 'SYN', 'price' => '10.57', 'type' => 'actions'],
            ['ticker' => 'CAMB3', 'name' => 'Cambuci', 'price' => '12.25', 'type' => 'actions'],
            ['ticker' => 'ALLD3', 'name' => 'Allied', 'price' => '7.56', 'type' => 'actions'],
            ['ticker' => 'ENGI4', 'name' => 'Energisa', 'price' => '8.45', 'type' => 'actions'],
            ['ticker' => 'RNEW3', 'name' => 'Renova Energia', 'price' => '0.88', 'type' => 'actions'],
            ['ticker' => 'EUCA4', 'name' => 'Eucatex', 'price' => '15.26', 'type' => 'actions'],
            ['ticker' => 'DMVF3', 'name' => 'D1000 Varejo Farma', 'price' => '7.35', 'type' => 'actions'],
            ['ticker' => 'IGTI3', 'name' => 'Iguatemi', 'price' => '2.96', 'type' => 'actions'],
            ['ticker' => 'IGTI3', 'name' => 'Jereissati Participações', 'price' => '2.96', 'type' => 'actions'],
            ['ticker' => 'TASA3', 'name' => 'Taurus', 'price' => '11.17', 'type' => 'actions'],
            ['ticker' => 'LAND3', 'name' => 'Terra Santa', 'price' => '13.2', 'type' => 'actions'],
            ['ticker' => 'AALR3', 'name' => 'Alliança', 'price' => '10.44', 'type' => 'actions'],
            ['ticker' => 'UCAS3', 'name' => 'Unicasa', 'price' => '2.28', 'type' => 'actions'],
            ['ticker' => 'RSID3', 'name' => 'Rossi Residencial', 'price' => '3.68', 'type' => 'actions'],
            ['ticker' => 'RPMG3', 'name' => 'Refinaria de Manguinhos', 'price' => '2.64', 'type' => 'actions'],
            ['ticker' => 'SCAR3', 'name' => 'São Carlos', 'price' => '23.41', 'type' => 'actions'],
            ['ticker' => 'ALUP4', 'name' => 'Alupar', 'price' => '10.74', 'type' => 'actions'],
            ['ticker' => 'NUTR3', 'name' => 'Nutriplant', 'price' => '5.26', 'type' => 'actions'],
            ['ticker' => 'FHER3', 'name' => 'Fertilizantes Heringer', 'price' => '4.27', 'type' => 'actions'],
            ['ticker' => 'LVTC3', 'name' => 'WDC Networks', 'price' => '3.85', 'type' => 'actions'],
            ['ticker' => 'BRKM3', 'name' => 'Braskem', 'price' => '16.87', 'type' => 'actions'],
            ['ticker' => 'BIOM11', 'name' => 'BIOM11', 'price' => '0.34', 'type' => 'actions'],
            ['ticker' => 'BMEB4', 'name' => 'Banco Mercantil do Brasil', 'price' => '37.11', 'type' => 'actions'],
            ['ticker' => 'ENGI3', 'name' => 'Energisa', 'price' => '14.55', 'type' => 'actions'],
            ['ticker' => 'AVLL3', 'name' => 'Alphaville', 'price' => '4.2', 'type' => 'actions'],
            ['ticker' => 'WEST3', 'name' => 'Westwing', 'price' => '0.93', 'type' => 'actions'],
            ['ticker' => 'AMAR11', 'name' => 'AMAR11', 'price' => '0.76', 'type' => 'actions'],
            ['ticker' => 'BOBR4', 'name' => 'Bombril', 'price' => '1.98', 'type' => 'actions'],
            ['ticker' => 'EPAR3', 'name' => 'Embpar Participações', 'price' => '5.76', 'type' => 'actions'],
            ['ticker' => 'BPAC3', 'name' => 'Banco BTG Pactual', 'price' => '16.41', 'type' => 'actions'],
            ['ticker' => 'PDTC3', 'name' => 'Padtec', 'price' => '1.81', 'type' => 'actions'],
            ['ticker' => 'BRSR3', 'name' => 'Banrisul', 'price' => '12.81', 'type' => 'actions'],
            ['ticker' => 'LOGN3', 'name' => 'Log-In', 'price' => '35.82', 'type' => 'actions'],
            ['ticker' => 'CEBR6', 'name' => 'CEB', 'price' => '17.51', 'type' => 'actions'],
            ['ticker' => 'DOTZ3', 'name' => 'Dotz', 'price' => '5.51', 'type' => 'actions'],
            ['ticker' => 'CSRN3', 'name' => 'COSERN', 'price' => '15.46', 'type' => 'actions'],
            ['ticker' => 'EALT4', 'name' => 'Electro Aço Altona', 'price' => '14.14', 'type' => 'actions'],
            ['ticker' => 'ALUP3', 'name' => 'Alupar', 'price' => '11.3', 'type' => 'actions'],
            ['ticker' => 'SGPS3', 'name' => 'Springs', 'price' => '1.75', 'type' => 'actions'],
            ['ticker' => 'BEES3', 'name' => 'Banestes', 'price' => '8.93', 'type' => 'actions'],
            ['ticker' => 'RAPT3', 'name' => 'Randon', 'price' => '09.02', 'type' => 'actions'],
            ['ticker' => 'COCE5', 'name' => 'Coelce', 'price' => '31.5', 'type' => 'actions'],
            ['ticker' => 'ALPA3', 'name' => 'Alpargatas', 'price' => '7.86', 'type' => 'actions'],
            ['ticker' => 'ATOM3', 'name' => 'ATOM', 'price' => '1.99', 'type' => 'actions'],
            ['ticker' => 'CGRA4', 'name' => 'Grazziotin', 'price' => '25.21', 'type' => 'actions'],
            ['ticker' => 'UNIP3', 'name' => 'Unipar', 'price' => '49', 'type' => 'actions'],
            ['ticker' => 'CGRA3', 'name' => 'Grazziotin', 'price' => '24.8', 'type' => 'actions'],
            ['ticker' => 'BEES4', 'name' => 'Banestes', 'price' => '9.93', 'type' => 'actions'],
            ['ticker' => 'NINJ3', 'name' => 'GetNinjas', 'price' => '4.72', 'type' => 'actions'],
            ['ticker' => 'CEBR5', 'name' => 'CEB', 'price' => '16.83', 'type' => 'actions'],
            ['ticker' => 'NORD3', 'name' => 'Nordon', 'price' => '10.37', 'type' => 'actions'],
            ['ticker' => 'INEP4', 'name' => 'Inepar', 'price' => '1.88', 'type' => 'actions'],
            ['ticker' => 'CLSC4', 'name' => 'Celesc', 'price' => '74.66', 'type' => 'actions'],
            ['ticker' => 'PTNT4', 'name' => 'Pettenati', 'price' => '06.03', 'type' => 'actions'],
            ['ticker' => 'BAZA3', 'name' => 'Banco da Amazônia', 'price' => '96.01', 'type' => 'actions'],
            ['ticker' => 'TELB4', 'name' => 'Telebras', 'price' => '9.46', 'type' => 'actions'],
            ['ticker' => 'CEDO4', 'name' => 'Cedro Têxtil', 'price' => '23.79', 'type' => 'actions'],
            ['ticker' => 'BPAC5', 'name' => 'Banco BTG Pactual', 'price' => '9.28', 'type' => 'actions'],
            ['ticker' => 'RDNI3', 'name' => 'RNI', 'price' => '3.14', 'type' => 'actions'],
            ['ticker' => 'TRPL3', 'name' => 'Transmissão Paulista', 'price' => '32', 'type' => 'actions'],
            ['ticker' => 'MGEL4', 'name' => 'Mangels', 'price' => '12.2', 'type' => 'actions'],
            ['ticker' => 'HAGA4', 'name' => 'Haga', 'price' => '1.17', 'type' => 'actions'],
            ['ticker' => 'EMAE4', 'name' => 'EMAE', 'price' => '41', 'type' => 'actions'],
            ['ticker' => 'DOHL4', 'name' => 'Döhler', 'price' => '4.19', 'type' => 'actions'],
            ['ticker' => 'CGAS5', 'name' => 'Comgás', 'price' => '113.59', 'type' => 'actions'],
            ['ticker' => 'EQPA3', 'name' => 'Equatorial Energia Pará', 'price' => '6.95', 'type' => 'actions'],
            ['ticker' => 'HAGA3', 'name' => 'Haga', 'price' => '2.39', 'type' => 'actions'],
            ['ticker' => 'VSTE3', 'name' => 'LE LIS BLANC', 'price' => '13.09', 'type' => 'actions'],
            ['ticker' => 'WHRL4', 'name' => 'Whirlpool', 'price' => '4.46', 'type' => 'actions'],
            ['ticker' => 'CTNM4', 'name' => 'Coteminas', 'price' => '0.88', 'type' => 'actions'],
            ['ticker' => 'CEBR3', 'name' => 'CEB', 'price' => '19.45', 'type' => 'actions'],
            ['ticker' => 'MTSA4', 'name' => 'Metisa', 'price' => '44.39', 'type' => 'actions'],
            ['ticker' => 'REDE3', 'name' => 'Rede Energia', 'price' => '7', 'type' => 'actions'],
            ['ticker' => 'CTSA3', 'name' => 'Santanense', 'price' => '2.85', 'type' => 'actions'],
            ['ticker' => 'WHRL3', 'name' => 'Whirlpool', 'price' => '4.19', 'type' => 'actions'],
            ['ticker' => 'BMEB3', 'name' => 'Banco Mercantil do Brasil', 'price' => '34.8', 'type' => 'actions'],
            ['ticker' => 'CRPG5', 'name' => 'Tronox Pigmentos', 'price' => '28.8', 'type' => 'actions'],
            ['ticker' => 'MNPR3', 'name' => 'Minupar', 'price' => '16.4', 'type' => 'actions'],
            ['ticker' => 'EKTR4', 'name' => 'Elektro', 'price' => '41.8', 'type' => 'actions'],
            ['ticker' => 'WLMM4', 'name' => 'WLM', 'price' => '32', 'type' => 'actions'],
            ['ticker' => 'AZEV11', 'name' => 'Azevedo & Travassos', 'price' => '0.46', 'type' => 'actions'],
            ['ticker' => 'UNIP5', 'name' => 'Unipar', 'price' => '49.5', 'type' => 'actions'],
            ['ticker' => 'OIBR4', 'name' => 'Oi', 'price' => '12.14', 'type' => 'actions'],
            ['ticker' => 'RSUL4', 'name' => 'Metalúrgica Riosulense', 'price' => '63.29', 'type' => 'actions'],
            ['ticker' => 'EQMA3B', 'name' => 'Equatorial Maranhão', 'price' => '25.49', 'type' => 'actions'],
            ['ticker' => 'OFSA3', 'name' => 'Ourofino Saúde Animal', 'price' => '22.37', 'type' => 'actions'],
            ['ticker' => 'EALT3', 'name' => 'Electro Aço Altona', 'price' => '14', 'type' => 'actions'],
            ['ticker' => 'EUCA3', 'name' => 'Eucatex', 'price' => '16.7', 'type' => 'actions'],
            ['ticker' => 'PTNT3', 'name' => 'Pettenati', 'price' => '09.02', 'type' => 'actions'],
            ['ticker' => 'CRPG6', 'name' => 'Tronox Pigmentos', 'price' => '29.59', 'type' => 'actions'],
            ['ticker' => 'BSLI3', 'name' => 'Banco de Brasília', 'price' => '10.93', 'type' => 'actions'],
            ['ticker' => 'SNSY3', 'name' => 'Sansuy', 'price' => '12.64', 'type' => 'actions'],
            ['ticker' => 'PINE3', 'name' => 'Banco Pine', 'price' => '5.7', 'type' => 'actions'],
            ['ticker' => 'OSXB3', 'name' => 'OSX Brasil', 'price' => '3.72', 'type' => 'actions'],
            ['ticker' => 'RPAD6', 'name' => 'Alfa Holdings', 'price' => '8.73', 'type' => 'actions'],
            ['ticker' => 'CGAS3', 'name' => 'Comgás', 'price' => '108.03', 'type' => 'actions'],
            ['ticker' => 'GEPA4', 'name' => 'Rio Paranapanema Energia', 'price' => '26.44', 'type' => 'actions'],
            ['ticker' => 'BALM4', 'name' => 'Baumer', 'price' => '10.49', 'type' => 'actions'],
            ['ticker' => 'NEXP3', 'name' => 'Brasil Brokers', 'price' => '4.16', 'type' => 'actions'],
            ['ticker' => 'PEAB3', 'name' => 'Participações Aliança da Bahia', 'price' => '43', 'type' => 'actions'],
            ['ticker' => 'BGIP4', 'name' => 'Banese', 'price' => '24', 'type' => 'actions'],
            ['ticker' => 'BDLL4', 'name' => 'Bardella', 'price' => '9.2', 'type' => 'actions'],
            ['ticker' => 'PLAS3', 'name' => 'Plascar', 'price' => '5.5', 'type' => 'actions'],
            ['ticker' => 'ATMP3', 'name' => 'Atma', 'price' => '1.6', 'type' => 'actions'],
            ['ticker' => 'ENMT4', 'name' => 'Energisa MT', 'price' => '72', 'type' => 'actions'],
            ['ticker' => 'BGIP3', 'name' => 'Banese', 'price' => '24.5', 'type' => 'actions'],
            ['ticker' => 'CEED3', 'name' => 'CEEE D', 'price' => '13', 'type' => 'actions'],
            ['ticker' => 'BSLI4', 'name' => 'Banco de Brasília', 'price' => '9.97', 'type' => 'actions'],
            ['ticker' => 'ESTR4', 'name' => 'Estrela', 'price' => '02.07', 'type' => 'actions'],
            ['ticker' => 'BNBR3', 'name' => 'Banco do Nordeste', 'price' => '101.5', 'type' => 'actions'],
            ['ticker' => 'APER3', 'name' => 'Alper', 'price' => '46.33', 'type' => 'actions'],
            ['ticker' => 'HBTS5', 'name' => 'Habitasul', 'price' => '40.2', 'type' => 'actions'],
            ['ticker' => 'COCE3', 'name' => 'Coelce', 'price' => '33', 'type' => 'actions'],
            ['ticker' => 'BRSR5', 'name' => 'Banrisul', 'price' => '17', 'type' => 'actions'],
            ['ticker' => 'CTKA4', 'name' => 'Karsten', 'price' => '15.46', 'type' => 'actions'],
            ['ticker' => 'TELB3', 'name' => 'Telebras', 'price' => '13.9', 'type' => 'actions'],
            ['ticker' => 'CPLE5', 'name' => 'Copel', 'price' => '12.28', 'type' => 'actions'],
            ['ticker' => 'HETA4', 'name' => 'Hercules', 'price' => '5.21', 'type' => 'actions'],
            ['ticker' => 'BMKS3', 'name' => 'Monark', 'price' => '313', 'type' => 'actions'],
            ['ticker' => 'SNSY5', 'name' => 'Sansuy', 'price' => '5.85', 'type' => 'actions'],
            ['ticker' => 'CSRN5', 'name' => 'COSERN', 'price' => '18.5', 'type' => 'actions'],
            ['ticker' => 'FESA3', 'name' => 'Ferbasa', 'price' => '14.18', 'type' => 'actions'],
            ['ticker' => 'BAHI3', 'name' => 'Bahema', 'price' => '6.5', 'type' => 'actions'],
            ['ticker' => 'HOOT4', 'name' => 'Hotéis Othon', 'price' => '2.38', 'type' => 'actions'],
            ['ticker' => 'CEDO3', 'name' => 'Cedro Têxtil', 'price' => '26.1', 'type' => 'actions'],
            ['ticker' => 'USIM6', 'name' => 'Usiminas', 'price' => '12.01', 'type' => 'actions'],
            ['ticker' => 'AHEB3', 'name' => 'São Paulo Turismo', 'price' => '35', 'type' => 'actions'],
            ['ticker' => 'CSRN6', 'name' => 'COSERN', 'price' => '16.66', 'type' => 'actions'],
            ['ticker' => 'CEEB3', 'name' => 'COELBA', 'price' => '39.63', 'type' => 'actions'],
            ['ticker' => 'IGTI4', 'name' => 'Iguatemi', 'price' => '10.1', 'type' => 'actions'],
            ['ticker' => 'IGTI4', 'name' => 'Jereissati Participações', 'price' => '10.1', 'type' => 'actions'],
            ['ticker' => 'CTNM3', 'name' => 'Coteminas', 'price' => '7.13', 'type' => 'actions'],
            ['ticker' => 'GEPA3', 'name' => 'Rio Paranapanema Energia', 'price' => '25.01', 'type' => 'actions'],
            ['ticker' => 'CLSC3', 'name' => 'Celesc', 'price' => '70.5', 'type' => 'actions'],
            ['ticker' => 'PINE11', 'name' => 'Banco Pine', 'price' => '6.44', 'type' => 'actions'],
            ['ticker' => 'MAPT3', 'name' => 'Cemepe', 'price' => '4.21', 'type' => 'actions'],
            ['ticker' => 'BAUH4', 'name' => 'Excelsior', 'price' => '78.89', 'type' => 'actions'],
            ['ticker' => 'WLMM3', 'name' => 'WLM', 'price' => '27.83', 'type' => 'actions'],
            ['ticker' => 'MNDL3', 'name' => 'Mundial', 'price' => '14', 'type' => 'actions'],
            ['ticker' => 'FRIO3', 'name' => 'Metalfrio', 'price' => '169', 'type' => 'actions'],
            ['ticker' => 'AFLT3', 'name' => 'Afluente T', 'price' => '7.24', 'type' => 'actions'],
            ['ticker' => 'RPAD5', 'name' => 'Alfa Holdings', 'price' => '8.56', 'type' => 'actions'],
            ['ticker' => 'ENMT3', 'name' => 'Energisa MT', 'price' => '83.7', 'type' => 'actions'],
            ['ticker' => 'MAPT4', 'name' => 'Cemepe', 'price' => '5.59', 'type' => 'actions'],
            ['ticker' => 'MWET4', 'name' => 'Wetzel', 'price' => '9.34', 'type' => 'actions'],
            ['ticker' => 'LIPR3', 'name' => 'Eletropar', 'price' => '47.18', 'type' => 'actions'],
            ['ticker' => 'MRSA6B', 'name' => 'MRS Logística', 'price' => '32.99', 'type' => 'actions'],
            ['ticker' => 'PATI3', 'name' => 'Panatlântica', 'price' => '24', 'type' => 'actions'],
            ['ticker' => 'BALM3', 'name' => 'Baumer', 'price' => '12.5', 'type' => 'actions'],
            ['ticker' => 'PSVM11', 'name' => 'PSVM11', 'price' => '6.72', 'type' => 'actions'],
            ['ticker' => 'EQPA5', 'name' => 'Equatorial Energia Pará', 'price' => '8', 'type' => 'actions'],
            ['ticker' => 'LUXM4', 'name' => 'Trevisa', 'price' => '14', 'type' => 'actions'],
            ['ticker' => 'BRKM6', 'name' => 'Braskem', 'price' => '13.5', 'type' => 'actions'],
            ['ticker' => 'TEKA4', 'name' => 'Teka', 'price' => '31', 'type' => 'actions'],
            ['ticker' => 'MOAR3', 'name' => 'Monteiro Aranha', 'price' => '397.87', 'type' => 'actions'],
            ['ticker' => 'MERC4', 'name' => 'Mercantil do Brasil Financeira', 'price' => '9.31', 'type' => 'actions'],
            ['ticker' => 'DTCY3', 'name' => 'Dtcom', 'price' => '6.86', 'type' => 'actions'],
            ['ticker' => 'MRSA3B', 'name' => 'MRS Logística', 'price' => '32.99', 'type' => 'actions'],
            ['ticker' => 'FIEI3', 'name' => 'Fica', 'price' => '11.85', 'type' => 'actions'],
            ['ticker' => 'BMIN4', 'name' => 'Banco Mercantil de Investimentos', 'price' => '15.55', 'type' => 'actions'],
            ['ticker' => 'ELET5', 'name' => 'Eletrobras', 'price' => '95', 'type' => 'actions'],
            ['ticker' => 'BDLL3', 'name' => 'Bardella', 'price' => '13.01', 'type' => 'actions'],
            ['ticker' => 'GSHP3', 'name' => 'General Shopping & Outlets', 'price' => '10.5', 'type' => 'actions'],
            ['ticker' => 'MRSA5B', 'name' => 'MRS Logística', 'price' => '30', 'type' => 'actions'],
            ['ticker' => 'RPAD3', 'name' => 'Alfa Holdings', 'price' => '8.84', 'type' => 'actions'],
            ['ticker' => 'JOPA3', 'name' => 'Josapar', 'price' => '21', 'type' => 'actions'],
            ['ticker' => 'BMIN3', 'name' => 'Banco Mercantil de Investimentos', 'price' => '19.62', 'type' => 'actions'],
            ['ticker' => 'EKTR3', 'name' => 'Elektro', 'price' => '40.03', 'type' => 'actions']
        ];

        foreach ($actions as $action) {
            $a = app(Active::class)->firstOrNew(
                $action
            );

            $a->save();
        }
    }
}
