<?php

namespace Database\Seeders;

use App\Models\Active;
use Illuminate\Database\Seeder;

class FundsSeeder extends Seeder
{

    public function run(): void
    {
        $funds =
        [
            ['ticker' => 'KNRE11', 'name' => 'Kinea II Real Estate Equity', 'price' => '0.42', 'type' => 'real_estate_funds'],
            ['ticker' => 'AROA11', 'name' => 'Aroeira 333 Renda Logística', 'price' => '0.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'RCFA11', 'name' => 'Grupo RCFA', 'price' => '1', 'type' => 'real_estate_funds'],
            ['ticker' => 'PRTS11', 'name' => 'Multi Properties', 'price' => '1', 'type' => 'real_estate_funds'],
            ['ticker' => 'TORD11', 'name' => 'Tordesilhas EI', 'price' => '1.38', 'type' => 'real_estate_funds'],
            ['ticker' => 'PRSN11B', 'name' => 'Personale I', 'price' => '1.48', 'type' => 'real_estate_funds'],
            ['ticker' => 'CNES11', 'name' => 'Cenesp', 'price' => '1.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'CARE11', 'name' => 'Brazilian GraveyardDeath Care', 'price' => '1.63', 'type' => 'real_estate_funds'],
            ['ticker' => 'SCPF11', 'name' => 'SCP', 'price' => '2.71', 'type' => 'real_estate_funds'],
            ['ticker' => 'FIVN11', 'name' => 'Vida Nova', 'price' => '2.74', 'type' => 'real_estate_funds'],
            ['ticker' => 'SRVD11', 'name' => 'Serra Verde', 'price' => '3', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBDS11', 'name' => 'RB Capital Desenvolvimento Residencial II', 'price' => '3', 'type' => 'real_estate_funds'],
            ['ticker' => 'IAGR11', 'name' => 'SFI Investimentos do Agronegócio Fiagro', 'price' => '3.17', 'type' => 'real_estate_funds'],
            ['ticker' => 'HRDF11', 'name' => 'Hedge Realty Development', 'price' => '3.2', 'type' => 'real_estate_funds'],
            ['ticker' => 'VSLH11', 'name' => 'Versalhes Recebíveis Imobiliários', 'price' => '3.38', 'type' => 'real_estate_funds'],
            ['ticker' => 'VSEC11', 'name' => 'Votorantim Securities', 'price' => '3.49', 'type' => 'real_estate_funds'],
            ['ticker' => 'EGYR11', 'name' => 'Energy Resort', 'price' => '04.06', 'type' => 'real_estate_funds'],
            ['ticker' => 'VINO11', 'name' => 'Vinci Offices', 'price' => '06.02', 'type' => 'real_estate_funds'],
            ['ticker' => 'VIUR11', 'name' => 'Vinci Imóveis Urbanos', 'price' => '6.48', 'type' => 'real_estate_funds'],
            ['ticker' => 'BLMR11', 'name' => 'VBI Renda + FOF', 'price' => '6.78', 'type' => 'real_estate_funds'],
            ['ticker' => 'DPRO11', 'name' => 'Devant Properties', 'price' => '6.96', 'type' => 'real_estate_funds'],
            ['ticker' => 'BIME11', 'name' => 'Brio Multiestratégia', 'price' => '7.22', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPSF11', 'name' => 'XP Selection', 'price' => '7.45', 'type' => 'real_estate_funds'],
            ['ticker' => 'IDGR11', 'name' => 'Unidades Autônomas II', 'price' => '7.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRF11', 'name' => 'RBR Alpha Multiestratégia Real Estate', 'price' => '7.54', 'type' => 'real_estate_funds'],
            ['ticker' => 'DVFF11', 'name' => 'Devant Fundo de Fundos', 'price' => '7.57', 'type' => 'real_estate_funds'],
            ['ticker' => 'ALZM11', 'name' => 'Alianza Multiestratégia', 'price' => '7.74', 'type' => 'real_estate_funds'],
            ['ticker' => 'AAZQ11', 'name' => 'AZ Quest Fiagro', 'price' => '7.77', 'type' => 'real_estate_funds'],
            ['ticker' => 'OIAG11', 'name' => 'Ourinvest Innovation Fiagro', 'price' => '7.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'GSFI11', 'name' => 'General Shopping e Outlets', 'price' => '8', 'type' => 'real_estate_funds'],
            ['ticker' => 'CTXT11', 'name' => 'Centro Têxtil Internacional', 'price' => '08.02', 'type' => 'real_estate_funds'],
            ['ticker' => 'VIFI11', 'name' => 'Vinci Instrumentos Financeiros', 'price' => '08.09', 'type' => 'real_estate_funds'],
            ['ticker' => 'CPTR11', 'name' => 'Capitânia Agro Strategies Fiagro', 'price' => '8.12', 'type' => 'real_estate_funds'],
            ['ticker' => 'KISU11', 'name' => 'Kilima FoF Suno 30', 'price' => '8.15', 'type' => 'real_estate_funds'],
            ['ticker' => 'CPTS11', 'name' => 'Capitânia Securities II', 'price' => '8.23', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPCM11', 'name' => 'XP Corporate Macaé', 'price' => '8.24', 'type' => 'real_estate_funds'],
            ['ticker' => 'AJFI11', 'name' => 'AJ Malls', 'price' => '8.28', 'type' => 'real_estate_funds'],
            ['ticker' => 'BCFF11', 'name' => 'BTG Pactual Fundo de Fundos', 'price' => '8.28', 'type' => 'real_estate_funds'],
            ['ticker' => 'VGIA11', 'name' => 'Valora CRA Fiagro', 'price' => '8.32', 'type' => 'real_estate_funds'],
            ['ticker' => 'DCRA11', 'name' => 'Devant Fiagro', 'price' => '8.33', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPCA11', 'name' => 'XP Crédito Agrícola Fiagro', 'price' => '8.34', 'type' => 'real_estate_funds'],
            ['ticker' => 'RZAG11', 'name' => 'Riza Agro Fiagro', 'price' => '8.45', 'type' => 'real_estate_funds'],
            ['ticker' => 'HREC11', 'name' => 'Hedge Recebíveis Imobiliários', 'price' => '8.53', 'type' => 'real_estate_funds'],
            ['ticker' => 'VCRI11', 'name' => 'Vinci Credit Securities', 'price' => '8.53', 'type' => 'real_estate_funds'],
            ['ticker' => 'FGAA11', 'name' => 'FG/Agro Fiagro', 'price' => '8.61', 'type' => 'real_estate_funds'],
            ['ticker' => 'NCRA11', 'name' => 'NCH Recebíveis do Agronegócio Fiagro', 'price' => '8.67', 'type' => 'real_estate_funds'],
            ['ticker' => 'NCRI11', 'name' => 'Navi Crédito Imobiliário', 'price' => '8.69', 'type' => 'real_estate_funds'],
            ['ticker' => 'OGHY11', 'name' => 'Órama High Yield', 'price' => '8.72', 'type' => 'real_estate_funds'],
            ['ticker' => 'IDFI11', 'name' => 'Unidades Autônomas', 'price' => '8.73', 'type' => 'real_estate_funds'],
            ['ticker' => 'VGHF11', 'name' => 'Valora Hedge Fund', 'price' => '8.78', 'type' => 'real_estate_funds'],
            ['ticker' => 'TOUR11', 'name' => 'Tourmalet II', 'price' => '8.8', 'type' => 'real_estate_funds'],
            ['ticker' => 'PORD11', 'name' => 'Polo Crédito Imobiliário', 'price' => '8.94', 'type' => 'real_estate_funds'],
            ['ticker' => 'RENV11', 'name' => 'CPV Energia', 'price' => '9', 'type' => 'real_estate_funds'],
            ['ticker' => 'ARRI11', 'name' => 'Open K Ativos e Recebiveis Imobiliarios', 'price' => '09.03', 'type' => 'real_estate_funds'],
            ['ticker' => 'EQIR11', 'name' => 'EQI Recebíveis Imobiliários', 'price' => '09.03', 'type' => 'real_estate_funds'],
            ['ticker' => 'VGRI11', 'name' => 'Valora Renda Imobiliária', 'price' => '09.04', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRX11', 'name' => 'RBR Plus Multiestratégia Real Estate', 'price' => '09.07', 'type' => 'real_estate_funds'],
            ['ticker' => 'GARE11', 'name' => 'Guardian Real Estate', 'price' => '09.09', 'type' => 'real_estate_funds'],
            ['ticker' => 'MCHF11', 'name' => 'Mauá Capital Hedge Fund', 'price' => '9.1', 'type' => 'real_estate_funds'],
            ['ticker' => 'GAME11', 'name' => 'Guardian Multiestratégia Imobiliária I', 'price' => '9.14', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNSC11', 'name' => 'Kinea Securities', 'price' => '9.16', 'type' => 'real_estate_funds'],
            ['ticker' => 'EXES11', 'name' => 'Exes', 'price' => '9.21', 'type' => 'real_estate_funds'],
            ['ticker' => 'BODB11', 'name' => 'Bocaina FI-Infra', 'price' => '9.26', 'type' => 'real_estate_funds'],
            ['ticker' => 'NCHB11', 'name' => 'NCH Brasil Recebíveis Imobiliários', 'price' => '9.31', 'type' => 'real_estate_funds'],
            ['ticker' => 'SPXS11', 'name' => 'SPX SYN Multiestratégia', 'price' => '9.31', 'type' => 'real_estate_funds'],
            ['ticker' => 'SNEL11', 'name' => 'Suno Energias Limpas FII', 'price' => '9.33', 'type' => 'real_estate_funds'],
            ['ticker' => 'MANA11', 'name' => 'Manatí Capital Hedge Fund', 'price' => '9.36', 'type' => 'real_estate_funds'],
            ['ticker' => 'MGCR11', 'name' => 'Mogno CRIs Multiestratégia', 'price' => '9.4', 'type' => 'real_estate_funds'],
            ['ticker' => 'MCHY11', 'name' => 'Mauá Capital Real Estate', 'price' => '9.46', 'type' => 'real_estate_funds'],
            ['ticker' => 'BBIG11', 'name' => 'BB Premium Malls', 'price' => '9.48', 'type' => 'real_estate_funds'],
            ['ticker' => 'PULV11', 'name' => 'RBR Crédito Pulverizado Responsabilidade Limitada', 'price' => '9.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'LATR11B', 'name' => 'Lateres', 'price' => '9.51', 'type' => 'real_estate_funds'],
            ['ticker' => 'APTO11', 'name' => 'Navi Residencial', 'price' => '9.52', 'type' => 'real_estate_funds'],
            ['ticker' => 'PMIS11', 'name' => 'Paramis Hedge Fund', 'price' => '9.55', 'type' => 'real_estate_funds'],
            ['ticker' => 'KCRE11', 'name' => 'Kinea Creditas', 'price' => '9.62', 'type' => 'real_estate_funds'],
            ['ticker' => 'SNME11', 'name' => 'Suno Multiestratégia', 'price' => '9.7', 'type' => 'real_estate_funds'],
            ['ticker' => 'WHGR11', 'name' => 'WHG Real Estate', 'price' => '9.75', 'type' => 'real_estate_funds'],
            ['ticker' => 'CYCR11', 'name' => 'Cyrela Crédito', 'price' => '9.79', 'type' => 'real_estate_funds'],
            ['ticker' => 'AGRX11', 'name' => 'Exes Araguaia Fiagro', 'price' => '9.79', 'type' => 'real_estate_funds'],
            ['ticker' => 'VGIR11', 'name' => 'Valora CRI CDI', 'price' => '9.81', 'type' => 'real_estate_funds'],
            ['ticker' => 'KINP11', 'name' => 'Even Permuta Kinea', 'price' => '9.82', 'type' => 'real_estate_funds'],
            ['ticker' => 'RURA11', 'name' => 'Itaú Asset Rural Fiagro', 'price' => '9.84', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTCI11', 'name' => 'BTG Pactual Crédito Imobiliário', 'price' => '9.88', 'type' => 'real_estate_funds'],
            ['ticker' => 'PLRI11', 'name' => 'Polo', 'price' => '9.92', 'type' => 'real_estate_funds'],
            ['ticker' => 'OGIN11', 'name' => 'Nikos FIC-INFRA', 'price' => '9.94', 'type' => 'real_estate_funds'],
            ['ticker' => 'VVCR11', 'name' => 'V2 Recebíveis Imobiliários', 'price' => '9.95', 'type' => 'real_estate_funds'],
            ['ticker' => 'EVBI11', 'name' => 'HBC II', 'price' => '9.98', 'type' => 'real_estate_funds'],
            ['ticker' => 'GRWA11', 'name' => 'Greenwich Fiagro', 'price' => '10', 'type' => 'real_estate_funds'],
            ['ticker' => 'MXRF11', 'name' => 'Maxi Renda', 'price' => '10.03', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTYU11', 'name' => 'BTG Pactual You', 'price' => '10.13', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGBL11', 'name' => 'Hedge Brasil Logístico Industrial', 'price' => '10.17', 'type' => 'real_estate_funds'],
            ['ticker' => 'SNAG11', 'name' => 'Suno Agro Fiagro', 'price' => '10.24', 'type' => 'real_estate_funds'],
            ['ticker' => 'DAMA11', 'name' => 'Dama', 'price' => '10.45', 'type' => 'real_estate_funds'],
            ['ticker' => 'LIFE11', 'name' => 'Life Capital', 'price' => '10.48', 'type' => 'real_estate_funds'],
            ['ticker' => 'ZAVC11', 'name' => 'Zavit Crédito Imobiliário', 'price' => '10.49', 'type' => 'real_estate_funds'],
            ['ticker' => 'CCME11', 'name' => 'Canuma Capital Multiestratégia', 'price' => '10.53', 'type' => 'real_estate_funds'],
            ['ticker' => 'CPSH11', 'name' => 'Capitânia Shoppings', 'price' => '10.55', 'type' => 'real_estate_funds'],
            ['ticker' => 'CPLG11', 'name' => 'Capitânia Logística', 'price' => '10.6', 'type' => 'real_estate_funds'],
            ['ticker' => 'SPGM11', 'name' => 'SPGM', 'price' => '10.67', 'type' => 'real_estate_funds'],
            ['ticker' => 'GGRC11', 'name' => 'GGR Covepi', 'price' => '10.83', 'type' => 'real_estate_funds'],
            ['ticker' => 'IAAG11', 'name' => 'Inter Amerra', 'price' => '10.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'VRTM11', 'name' => 'Fator Verità Multiestratégia', 'price' => '11', 'type' => 'real_estate_funds'],
            ['ticker' => 'DAMT11B', 'name' => 'Diamante', 'price' => '11.45', 'type' => 'real_estate_funds'],
            ['ticker' => 'VPSI11', 'name' => 'Polo Shopping Indaiatuba', 'price' => '11.72', 'type' => 'real_estate_funds'],
            ['ticker' => 'ZAGH11', 'name' => 'Zagros Multiestratégia', 'price' => '12', 'type' => 'real_estate_funds'],
            ['ticker' => 'NPAR11', 'name' => 'Nestpar', 'price' => '12.82', 'type' => 'real_estate_funds'],
            ['ticker' => 'VVCO11', 'name' => 'V2 Edifícios Corporativos', 'price' => '12.93', 'type' => 'real_estate_funds'],
            ['ticker' => 'NVHO11', 'name' => 'Novo Horizonte', 'price' => '13', 'type' => 'real_estate_funds'],
            ['ticker' => 'PABY11', 'name' => 'Panamby', 'price' => '13.29', 'type' => 'real_estate_funds'],
            ['ticker' => 'FPOR11', 'name' => 'Porto Sudeste Royalties FIP-IE', 'price' => '15', 'type' => 'real_estate_funds'],
            ['ticker' => 'LFTT11', 'name' => 'Loft II', 'price' => '16', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBVO11', 'name' => 'Rio Bravo Crédito Imobiliário II', 'price' => '18', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGAG11', 'name' => 'High Fiagro', 'price' => '18.3', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPPR11', 'name' => 'XP Properties', 'price' => '18.4', 'type' => 'real_estate_funds'],
            ['ticker' => 'MGHT11', 'name' => 'Mogno Hoteis', 'price' => '18.49', 'type' => 'real_estate_funds'],
            ['ticker' => 'EDGA11', 'name' => 'Edifício Galeria', 'price' => '18.6', 'type' => 'real_estate_funds'],
            ['ticker' => 'BZLI11', 'name' => 'Brazil Realty', 'price' => '19.78', 'type' => 'real_estate_funds'],
            ['ticker' => 'NVIF11', 'name' => 'Nova I', 'price' => '24.24', 'type' => 'real_estate_funds'],
            ['ticker' => 'MFCR11', 'name' => 'Merito Recebíveis Imobiliários', 'price' => '26.64', 'type' => 'real_estate_funds'],
            ['ticker' => 'CBOP11', 'name' => 'Castello Branco Office Park', 'price' => '28.06', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBGS11', 'name' => 'RB Capital General Shopping Sulacap', 'price' => '28.45', 'type' => 'real_estate_funds'],
            ['ticker' => 'HCTR11', 'name' => 'Hectare CE', 'price' => '28.94', 'type' => 'real_estate_funds'],
            ['ticker' => 'HOFC11', 'name' => 'Hedge Office Income', 'price' => '29.62', 'type' => 'real_estate_funds'],
            ['ticker' => 'OULG11', 'name' => 'Ourinvest Logística', 'price' => '29.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'PEMA11', 'name' => 'Performa Real Estate', 'price' => '30', 'type' => 'real_estate_funds'],
            ['ticker' => 'ESUU11', 'name' => 'BB Votorantim Energia Sustentável I FIP-IE', 'price' => '32', 'type' => 'real_estate_funds'],
            ['ticker' => 'SNLG11', 'name' => 'Suno Log FII', 'price' => '32.51', 'type' => 'real_estate_funds'],
            ['ticker' => 'SAIC11', 'name' => 'SIA Corporate', 'price' => '34', 'type' => 'real_estate_funds'],
            ['ticker' => 'RECT11', 'name' => 'REC Renda Imobiliária', 'price' => '34.34', 'type' => 'real_estate_funds'],
            ['ticker' => 'HAAA11', 'name' => 'Hedge AAA', 'price' => '34.51', 'type' => 'real_estate_funds'],
            ['ticker' => 'PATC11', 'name' => 'Pátria Edifícios Corporativos', 'price' => '34.62', 'type' => 'real_estate_funds'],
            ['ticker' => 'ASMT11', 'name' => 'ASA Metropolis', 'price' => '37.02', 'type' => 'real_estate_funds'],
            ['ticker' => 'DEVA11', 'name' => 'Devant Recebíveis Imobiliários', 'price' => '37.73', 'type' => 'real_estate_funds'],
            ['ticker' => 'BLMG11', 'name' => 'BlueMacaw Logística', 'price' => '39.25', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRD11', 'name' => 'RB Capital Renda II', 'price' => '39.8', 'type' => 'real_estate_funds'],
            ['ticker' => 'SPTW11', 'name' => 'SP Downtown', 'price' => '40.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'SARE11', 'name' => 'Santander Renda de Aluguéis', 'price' => '40.56', 'type' => 'real_estate_funds'],
            ['ticker' => 'CXCE11', 'name' => 'Caixa Cedae', 'price' => '40.95', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTHI11', 'name' => 'BTG Pactual Hotéis', 'price' => '41', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRS11', 'name' => 'Rio Bravo Renda Residencial', 'price' => '42.52', 'type' => 'real_estate_funds'],
            ['ticker' => 'CEOC11', 'name' => 'CEO Cyrela Commercial Properties', 'price' => '44.73', 'type' => 'real_estate_funds'],
            ['ticker' => 'RNGO11', 'name' => 'Rio Negro', 'price' => '45.98', 'type' => 'real_estate_funds'],
            ['ticker' => 'WTSP11', 'name' => 'Ourinvest RE I', 'price' => '46.2', 'type' => 'real_estate_funds'],
            ['ticker' => 'QAGR11', 'name' => 'VBI Agro', 'price' => '46.56', 'type' => 'real_estate_funds'],
            ['ticker' => 'PICE11', 'name' => 'Patria Infraestrutura Energia Core FIP-IE', 'price' => '46.93', 'type' => 'real_estate_funds'],
            ['ticker' => 'BICR11', 'name' => 'Inter Títulos Imobiliários', 'price' => '47.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'BROF11', 'name' => 'BRPR Corporate Offices', 'price' => '47.84', 'type' => 'real_estate_funds'],
            ['ticker' => 'FMOF11', 'name' => 'Memorial Office', 'price' => '48', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTRA11', 'name' => 'BTG Pactual Terras Agrícolas', 'price' => '49', 'type' => 'real_estate_funds'],
            ['ticker' => 'HCST11', 'name' => 'Hectare Desenvolvimento Student Housing', 'price' => '50', 'type' => 'real_estate_funds'],
            ['ticker' => 'BRCR11', 'name' => 'BTG Pactual Corporate Office Fund', 'price' => '50.63', 'type' => 'real_estate_funds'],
            ['ticker' => 'SEQR11', 'name' => 'Sequóia III Renda Imobiliária', 'price' => '51.98', 'type' => 'real_estate_funds'],
            ['ticker' => 'AIEC11', 'name' => 'Autonomy Edifícios Corporativos', 'price' => '54.87', 'type' => 'real_estate_funds'],
            ['ticker' => 'FIGS11', 'name' => 'General Shopping Ativo e Renda', 'price' => '54.97', 'type' => 'real_estate_funds'],
            ['ticker' => 'ATSA11', 'name' => 'Hedge Atrium Shopping Santo André', 'price' => '56', 'type' => 'real_estate_funds'],
            ['ticker' => 'GZIT11', 'name' => 'Gazit Malls', 'price' => '56.2', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRP11', 'name' => 'RBR Properties FII', 'price' => '56.39', 'type' => 'real_estate_funds'],
            ['ticker' => 'GCRA11', 'name' => 'Galapagos Recebíveis do Agronegócio Fiagro', 'price' => '58.53', 'type' => 'real_estate_funds'],
            ['ticker' => 'RELG11', 'name' => 'REC Logística', 'price' => '59.3', 'type' => 'real_estate_funds'],
            ['ticker' => 'SJAU11', 'name' => 'SJ AU Logística', 'price' => '59.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'WPLZ11', 'name' => 'West Plaza', 'price' => '59.56', 'type' => 'real_estate_funds'],
            ['ticker' => 'PQAG11', 'name' => 'Parque Anhanguera', 'price' => '59.78', 'type' => 'real_estate_funds'],
            ['ticker' => 'FISC11', 'name' => 'SC 401', 'price' => '60', 'type' => 'real_estate_funds'],
            ['ticker' => 'PRSV11', 'name' => 'Presidente Vargas', 'price' => '60', 'type' => 'real_estate_funds'],
            ['ticker' => 'ISCJ11', 'name' => 'Invista SCJ', 'price' => '60.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'PATL11', 'name' => 'Pátria Logística', 'price' => '60.26', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBFF11', 'name' => 'Rio Bravo Fundo de Fundos', 'price' => '61.09', 'type' => 'real_estate_funds'],
            ['ticker' => 'OUFF11', 'name' => 'Ourinvest Fundo de Fundos', 'price' => '61.1', 'type' => 'real_estate_funds'],
            ['ticker' => 'CJCT11', 'name' => 'Cidade Jardim Continental Tower', 'price' => '62.87', 'type' => 'real_estate_funds'],
            ['ticker' => 'RNDP11', 'name' => 'Fundo BB Renda de Papéis', 'price' => '62.96', 'type' => 'real_estate_funds'],
            ['ticker' => 'LSPA11', 'name' => 'Leste Riva Equity Preferencial I', 'price' => '63.19', 'type' => 'real_estate_funds'],
            ['ticker' => 'GLOG11', 'name' => 'Genial Logística', 'price' => '63.84', 'type' => 'real_estate_funds'],
            ['ticker' => 'GTLG11', 'name' => 'Gtis Brazil Logistics', 'price' => '63.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'MFAI11', 'name' => 'Mérito Fundos e Ações Imobiliárias', 'price' => '64.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'VIGT11', 'name' => 'Vinci Energia FIP-IE', 'price' => '64.63', 'type' => 'real_estate_funds'],
            ['ticker' => 'JSRE11', 'name' => 'JS Real Estate Multigestão', 'price' => '64.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBLG11', 'name' => 'RB Capital Logístico', 'price' => '65', 'type' => 'real_estate_funds'],
            ['ticker' => 'RECX11', 'name' => 'REC Fundo de Fundos', 'price' => '65', 'type' => 'real_estate_funds'],
            ['ticker' => 'VCRR11', 'name' => 'Vectis Renda Residencial', 'price' => '65.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'IBFF11', 'name' => 'FOF Integral Brei', 'price' => '66.4', 'type' => 'real_estate_funds'],
            ['ticker' => 'SHOP11', 'name' => 'Multi Shoppings', 'price' => '66.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'BCRI11', 'name' => 'Banestes Recebíveis Imobiliários', 'price' => '67.52', 'type' => 'real_estate_funds'],
            ['ticker' => 'PICE12', 'name' => 'Patria Infraestrutura Energia Core FIP-IE', 'price' => '67.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPID11', 'name' => 'XP FIC FI-Infra', 'price' => '68.26', 'type' => 'real_estate_funds'],
            ['ticker' => 'BPFF11', 'name' => 'Brasil Plural Absoluto Fundo de Fundos', 'price' => '68.49', 'type' => 'real_estate_funds'],
            ['ticker' => 'IBCR11', 'name' => 'CRI Integral Brei', 'price' => '68.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'GCFF11', 'name' => 'Galapagos Fundo de Fundos', 'price' => '69.3', 'type' => 'real_estate_funds'],
            ['ticker' => 'HCHG11', 'name' => 'Hectare Recebíveis High Grade', 'price' => '69.78', 'type' => 'real_estate_funds'],
            ['ticker' => 'HFOF11', 'name' => 'Hedge TOP FOFII 3', 'price' => '69.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'JFLL11', 'name' => 'JFL Living', 'price' => '70.39', 'type' => 'real_estate_funds'],
            ['ticker' => 'MGFF11', 'name' => 'Mogno Fundo de Fundos', 'price' => '70.4', 'type' => 'real_estate_funds'],
            ['ticker' => 'RFOF11', 'name' => 'RB Capital I Fundo de Fundos', 'price' => '70.75', 'type' => 'real_estate_funds'],
            ['ticker' => 'GCRI11', 'name' => 'Galapagos Recebíveis Imobiliários', 'price' => '70.98', 'type' => 'real_estate_funds'],
            ['ticker' => 'RMAI11', 'name' => 'REAG Multi Ativos Imobiliários', 'price' => '71.09', 'type' => 'real_estate_funds'],
            ['ticker' => 'CPFF11', 'name' => 'Capitânia REIT FOF', 'price' => '71.19', 'type' => 'real_estate_funds'],
            ['ticker' => 'ABCP11', 'name' => 'Grand Plaza Shopping', 'price' => '71.25', 'type' => 'real_estate_funds'],
            ['ticker' => 'FVPQ11', 'name' => 'Via Parque', 'price' => '71.51', 'type' => 'real_estate_funds'],
            ['ticker' => 'IRDM11', 'name' => 'Iridium Recebíveis Imobiliários', 'price' => '71.55', 'type' => 'real_estate_funds'],
            ['ticker' => 'VTPL11', 'name' => 'FII Plus', 'price' => '72.1', 'type' => 'real_estate_funds'],
            ['ticker' => 'CXCO11', 'name' => 'Caixa Imóveis Corporativos', 'price' => '72.43', 'type' => 'real_estate_funds'],
            ['ticker' => 'BBFO11', 'name' => 'BB Fundo de Fundos', 'price' => '72.78', 'type' => 'real_estate_funds'],
            ['ticker' => 'VSHO11', 'name' => 'Votorantim Shopping', 'price' => '73', 'type' => 'real_estate_funds'],
            ['ticker' => 'LUGG11', 'name' => 'Luggo', 'price' => '73.38', 'type' => 'real_estate_funds'],
            ['ticker' => 'IRIM11', 'name' => 'Iridium', 'price' => '73.54', 'type' => 'real_estate_funds'],
            ['ticker' => 'RVBI11', 'name' => 'VBI Reits Multiestratégia', 'price' => '74.34', 'type' => 'real_estate_funds'],
            ['ticker' => 'ITIT11', 'name' => 'Inter Teva Índice de Tijolo', 'price' => '75', 'type' => 'real_estate_funds'],
            ['ticker' => 'PNPR11', 'name' => 'Panorama Properties', 'price' => '75.53', 'type' => 'real_estate_funds'],
            ['ticker' => 'PFIN11', 'name' => 'Perfin Apollo Energia FIP-IE', 'price' => '75.79', 'type' => 'real_estate_funds'],
            ['ticker' => 'MORE11', 'name' => 'More Real Estate FOF', 'price' => '76.21', 'type' => 'real_estate_funds'],
            ['ticker' => 'RRCI11', 'name' => 'RB Capital Recebíveis Imobiliários', 'price' => '76.45', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPIE11', 'name' => 'XP Infra II FIP-IE', 'price' => '76.56', 'type' => 'real_estate_funds'],
            ['ticker' => 'CXAG11', 'name' => 'Caixa Agencias', 'price' => '77.14', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPIN11', 'name' => 'XP Industrial', 'price' => '77.2', 'type' => 'real_estate_funds'],
            ['ticker' => 'PLCA11', 'name' => 'Plural BRB Crédito Agro', 'price' => '77.32', 'type' => 'real_estate_funds'],
            ['ticker' => 'LLAO11', 'name' => 'BS2 Allinvestments', 'price' => '77.37', 'type' => 'real_estate_funds'],
            ['ticker' => 'CRFF11', 'name' => 'Caixa Rio Bravo Fundo de Fundos II', 'price' => '77.59', 'type' => 'real_estate_funds'],
            ['ticker' => 'VCRA11', 'name' => 'Vectis Datagro Crédito Agronegócio Fiagro', 'price' => '77.71', 'type' => 'real_estate_funds'],
            ['ticker' => 'OURE11', 'name' => 'Ourinvest Renda Estruturada', 'price' => '78', 'type' => 'real_estate_funds'],
            ['ticker' => 'BLMO11', 'name' => 'VBI Office Fund II', 'price' => '78', 'type' => 'real_estate_funds'],
            ['ticker' => 'QIRI11', 'name' => 'Quatá Imob Recebíveis Imobiliários', 'price' => '78.04', 'type' => 'real_estate_funds'],
            ['ticker' => 'MAXR11', 'name' => 'Max Retail', 'price' => '78.25', 'type' => 'real_estate_funds'],
            ['ticker' => 'TCPF11', 'name' => 'Treecorp Real Estate I', 'price' => '78.64', 'type' => 'real_estate_funds'],
            ['ticker' => 'CXRI11', 'name' => 'Caixa Rio Bravo Fundo de Fundos', 'price' => '78.66', 'type' => 'real_estate_funds'],
            ['ticker' => 'BLUR11', 'name' => 'Blue Recebíveis Imobiliários', 'price' => '79', 'type' => 'real_estate_funds'],
            ['ticker' => 'BARI11', 'name' => 'VBI Rendimentos Imobiliários I', 'price' => '79.05', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTAL11', 'name' => 'Btg Pactual Agro Logística', 'price' => '79.19', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRL11', 'name' => 'RBR Log', 'price' => '79.48', 'type' => 'real_estate_funds'],
            ['ticker' => 'OUJP11', 'name' => 'Ourinvest JPP', 'price' => '79.62', 'type' => 'real_estate_funds'],
            ['ticker' => 'ITIP11', 'name' => 'Inter Teva Índice de Papel', 'price' => '79.64', 'type' => 'real_estate_funds'],
            ['ticker' => 'VOTS11', 'name' => 'Tivio Securities', 'price' => '80.05', 'type' => 'real_estate_funds'],
            ['ticker' => 'NEWU11', 'name' => 'Newport Renda Urbana', 'price' => '80.75', 'type' => 'real_estate_funds'],
            ['ticker' => 'KIVO11', 'name' => 'Kilima Volkano Recebíveis', 'price' => '81.13', 'type' => 'real_estate_funds'],
            ['ticker' => 'JGPX11', 'name' => 'JGP Crédito Fiagro', 'price' => '81.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'URPR11', 'name' => 'Urca Prime Renda', 'price' => '81.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'BBGO11', 'name' => 'BB Crédito Fiagro', 'price' => '81.66', 'type' => 'real_estate_funds'],
            ['ticker' => 'JBFO11', 'name' => 'JBFO FOF', 'price' => '82.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'RZAK11', 'name' => 'Riza Akin', 'price' => '82.21', 'type' => 'real_estate_funds'],
            ['ticker' => 'GTWR11', 'name' => 'Green Towers', 'price' => '82.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'JPPA11', 'name' => 'JPP Capital Recebíveis Imobiliários', 'price' => '82.72', 'type' => 'real_estate_funds'],
            ['ticker' => 'CXCI11', 'name' => 'Caixa Carteira Imobiliária', 'price' => '82.84', 'type' => 'real_estate_funds'],
            ['ticker' => 'PNCR11', 'name' => 'Panorama Crédito Residencial', 'price' => '82.95', 'type' => 'real_estate_funds'],
            ['ticker' => 'DRIT11B', 'name' => 'Multigestão Renda Comercial', 'price' => '83.3', 'type' => 'real_estate_funds'],
            ['ticker' => 'HLOG11', 'name' => 'Hedge Logística', 'price' => '83.33', 'type' => 'real_estate_funds'],
            ['ticker' => 'RECR11', 'name' => 'REC Recebíveis Imobiliários', 'price' => '83.85', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBIR11', 'name' => 'RB Capital Desenvolvimento Residencial IV', 'price' => '83.95', 'type' => 'real_estate_funds'],
            ['ticker' => 'HSAF11', 'name' => 'HSI Ativos Financeiros', 'price' => '84', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBHG11', 'name' => 'Rio Bravo Crédito Imobiliário High Grade', 'price' => '84.21', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGFF11', 'name' => 'Pátria Imobiliário FOF', 'price' => '84.23', 'type' => 'real_estate_funds'],
            ['ticker' => 'QAMI11', 'name' => 'Quasar Crédito', 'price' => '84.68', 'type' => 'real_estate_funds'],
            ['ticker' => 'LSAG11', 'name' => 'Leste Fiagro', 'price' => '85.11', 'type' => 'real_estate_funds'],
            ['ticker' => 'LGCP11', 'name' => 'Log CP Inter', 'price' => '85.19', 'type' => 'real_estate_funds'],
            ['ticker' => 'AURB11', 'name' => 'Alianza Urban Hub Renda', 'price' => '85.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'HSLG11', 'name' => 'HSI Logística', 'price' => '85.6', 'type' => 'real_estate_funds'],
            ['ticker' => 'BLMC11', 'name' => 'VBI Crédito Imobiliário', 'price' => '85.75', 'type' => 'real_estate_funds'],
            ['ticker' => 'HUCG11', 'name' => 'Hospital Unimed Campina Grande', 'price' => '85.89', 'type' => 'real_estate_funds'],
            ['ticker' => 'JRDM11', 'name' => 'Shopping Jardim Sul', 'price' => '85.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'BPML11', 'name' => 'BTG Pactual Shoppings', 'price' => '85.91', 'type' => 'real_estate_funds'],
            ['ticker' => 'PLCR11', 'name' => 'Plural Recebíveis Imobiliários', 'price' => '85.97', 'type' => 'real_estate_funds'],
            ['ticker' => 'BDIF11', 'name' => 'BTG Pactual Dívida FI-Infra', 'price' => '85.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'NAVT11', 'name' => 'Navi Imobiliário Total Return', 'price' => '86.44', 'type' => 'real_estate_funds'],
            ['ticker' => 'WSEC11', 'name' => 'Warren Securities', 'price' => '86.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPCI11', 'name' => 'XP Crédito', 'price' => '86.59', 'type' => 'real_estate_funds'],
            ['ticker' => 'MATV11', 'name' => 'More Gestão Ativa de Recebíveis', 'price' => '86.63', 'type' => 'real_estate_funds'],
            ['ticker' => 'HABT11', 'name' => 'Habitat Recebíveis Pulverizados', 'price' => '88.3', 'type' => 'real_estate_funds'],
            ['ticker' => 'VGIP11', 'name' => 'Valora CRI Índice de Preço', 'price' => '88.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'MCCI11', 'name' => 'Mauá Capital Recebíveis Imobiliários', 'price' => '88.62', 'type' => 'real_estate_funds'],
            ['ticker' => 'TEPP11', 'name' => 'Tellus Properties', 'price' => '88.66', 'type' => 'real_estate_funds'],
            ['ticker' => 'VILG11', 'name' => 'Vinci Logística', 'price' => '89.02', 'type' => 'real_estate_funds'],
            ['ticker' => 'YUFI11', 'name' => 'Yuca', 'price' => '89.24', 'type' => 'real_estate_funds'],
            ['ticker' => 'VRTA11', 'name' => 'Fator Verità', 'price' => '89.38', 'type' => 'real_estate_funds'],
            ['ticker' => 'HPDP11', 'name' => 'Hedge Shopping Parque Dom Pedro', 'price' => '89.56', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBHY11', 'name' => 'Rio Bravo Crédito Imobiliário High Yield', 'price' => '89.7', 'type' => 'real_estate_funds'],
            ['ticker' => 'MORC11', 'name' => 'More Recebíveis Imobiliários', 'price' => '89.87', 'type' => 'real_estate_funds'],
            ['ticker' => 'KFOF11', 'name' => 'Kinea Fundo de Fundos', 'price' => '89.89', 'type' => 'real_estate_funds'],
            ['ticker' => 'SNFF11', 'name' => 'Suno Fundo de Fundos', 'price' => '89.94', 'type' => 'real_estate_funds'],
            ['ticker' => 'VVMR11', 'name' => 'Multi Renda Urbana', 'price' => '89.98', 'type' => 'real_estate_funds'],
            ['ticker' => 'RCFF11', 'name' => 'RBR Desenvolvimento Comercial Feeder FOF', 'price' => '90.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'SADI11', 'name' => 'Santander Papéis Imobiliários CDI', 'price' => '90', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRR11', 'name' => 'RBR Rendimentos High Grade', 'price' => '90.48', 'type' => 'real_estate_funds'],
            ['ticker' => 'BIDB11', 'name' => 'Inter FI-Infra', 'price' => '90.91', 'type' => 'real_estate_funds'],
            ['ticker' => 'VCJR11', 'name' => 'Vectis Juros Real', 'price' => '90.95', 'type' => 'real_estate_funds'],
            ['ticker' => 'BLCP11', 'name' => 'Bluecap Renda Logística', 'price' => '91', 'type' => 'real_estate_funds'],
            ['ticker' => 'SAPI11', 'name' => 'Santander Papéis Imobiliários', 'price' => '91.24', 'type' => 'real_estate_funds'],
            ['ticker' => 'EGAF11', 'name' => 'Ecoagro I Fiagro', 'price' => '91.85', 'type' => 'real_estate_funds'],
            ['ticker' => 'FATN11', 'name' => 'BRC Renda Corporativa', 'price' => '91.86', 'type' => 'real_estate_funds'],
            ['ticker' => 'ITRI11', 'name' => 'Itaú Total Return', 'price' => '92.04', 'type' => 'real_estate_funds'],
            ['ticker' => 'CCRF11', 'name' => 'RBR CRI', 'price' => '92.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'RPRI11', 'name' => 'RBR Premium Recebíveis Imobiliários', 'price' => '92.75', 'type' => 'real_estate_funds'],
            ['ticker' => 'ORPD11', 'name' => 'Ouro Verde Desenvolvimento Imobiliário', 'price' => '93', 'type' => 'real_estate_funds'],
            ['ticker' => 'RZTR11', 'name' => 'Riza Terrax', 'price' => '93.58', 'type' => 'real_estate_funds'],
            ['ticker' => 'CVBI11', 'name' => 'VBI CRI', 'price' => '93.65', 'type' => 'real_estate_funds'],
            ['ticker' => 'MINT11', 'name' => 'Mint Educacional', 'price' => '94', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBIF11', 'name' => 'Rio Bravo ESG FIC FI FI-Infra', 'price' => '94.15', 'type' => 'real_estate_funds'],
            ['ticker' => 'PVBI11', 'name' => 'VBI Prime Properties', 'price' => '94.28', 'type' => 'real_estate_funds'],
            ['ticker' => 'HSML11', 'name' => 'HSI Malls', 'price' => '94.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'PPEI11', 'name' => 'Prisma Proton Energia FIP-IE', 'price' => '94.64', 'type' => 'real_estate_funds'],
            ['ticker' => 'CLIN11', 'name' => 'Clave Índices de Preços', 'price' => '94.71', 'type' => 'real_estate_funds'],
            ['ticker' => 'TMPS11', 'name' => 'Itaú Tempus', 'price' => '94.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'OCRE11', 'name' => 'Octo FII', 'price' => '95', 'type' => 'real_estate_funds'],
            ['ticker' => 'HOSI11', 'name' => 'Housi', 'price' => '95.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'PURB11', 'name' => 'Plural Renda Urbana', 'price' => '95.1', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNIP11', 'name' => 'Kinea Índices de Preços', 'price' => '95.57', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRY11', 'name' => 'RBR Crédito Imobiliário Estruturado', 'price' => '95.62', 'type' => 'real_estate_funds'],
            ['ticker' => 'TRBL11', 'name' => 'Tellus Rio Bravo Renda Logística', 'price' => '95.91', 'type' => 'real_estate_funds'],
            ['ticker' => 'VTLT11', 'name' => 'Votorantim Logística', 'price' => '95.95', 'type' => 'real_estate_funds'],
            ['ticker' => 'ALZC11', 'name' => 'Alianza Crédito Imobiliário', 'price' => '96', 'type' => 'real_estate_funds'],
            ['ticker' => 'HDOF11', 'name' => 'Hedge Paladin Design Offices', 'price' => '96', 'type' => 'real_estate_funds'],
            ['ticker' => 'BMLC11', 'name' => 'BM Brascan Lajes Corporativas', 'price' => '96.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'CPTI11', 'name' => 'Capitânia FI-Infra', 'price' => '96.22', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNHF11', 'name' => 'Kinea Hedge Fund', 'price' => '96.35', 'type' => 'real_estate_funds'],
            ['ticker' => 'AFHI11', 'name' => 'AF Invest CRI', 'price' => '96.6', 'type' => 'real_estate_funds'],
            ['ticker' => 'RZAT11', 'name' => 'Riza Arctium Real Estate', 'price' => '97.59', 'type' => 'real_estate_funds'],
            ['ticker' => 'ICRI11', 'name' => 'Itaú Crédito Imobiliário IPCA', 'price' => '97.64', 'type' => 'real_estate_funds'],
            ['ticker' => 'FLCR11', 'name' => 'Faria Lima Capital Recebíveis Imobiliários I', 'price' => '97.85', 'type' => 'real_estate_funds'],
            ['ticker' => 'SNCI11', 'name' => 'Suno Recebíveis', 'price' => '97.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'VLOL11', 'name' => 'Vila Olímpia Corporate', 'price' => '98', 'type' => 'real_estate_funds'],
            ['ticker' => 'GCOI11', 'name' => 'Galapagos Special Oportunities', 'price' => '98.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'JSCR11', 'name' => 'JS Recebíveis Imobiliários', 'price' => '99', 'type' => 'real_estate_funds'],
            ['ticker' => 'CYLD11', 'name' => 'Cyrela Desenvolvimento Logístico', 'price' => '99', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGIC11', 'name' => 'HGI Créditos Imobiliários', 'price' => '99', 'type' => 'real_estate_funds'],
            ['ticker' => 'AZIN11', 'name' => 'AZ Quest Infra-Yield II FIP-IE', 'price' => '99.08', 'type' => 'real_estate_funds'],
            ['ticker' => 'JSAF11', 'name' => 'JS Ativos Financeiros', 'price' => '99.75', 'type' => 'real_estate_funds'],
            ['ticker' => 'AAGR11', 'name' => 'Asset Bank Fiagro', 'price' => '99.9', 'type' => 'real_estate_funds'],
            ['ticker' => 'APXM11', 'name' => 'Apex Malls', 'price' => '99.97', 'type' => 'real_estate_funds'],
            ['ticker' => 'HSRE11', 'name' => 'HSI Renda Imobiliária', 'price' => '99.98', 'type' => 'real_estate_funds'],
            ['ticker' => 'TCIN12', 'name' => 'G5 Cidade Nova (Cota Ordinária)', 'price' => '99.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'SMRE11', 'name' => 'Smart Real Estate', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'RDLI11', 'name' => 'RBR Desenvolvimento Logístico I', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'FLFL11', 'name' => 'VBI TR Faria Lima 4440', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'CENU11', 'name' => 'Cenu', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'ARXD11', 'name' => 'ARX Dover Recebíveis', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'TSER11', 'name' => 'Tishman Speyer Renda Corporativa', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'APXR11', 'name' => 'Apex Realty', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'SEED11', 'name' => 'Hedge Seed', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'PMFO11', 'name' => 'Speciale Real Estate Fund of Funds', 'price' => '100', 'type' => 'real_estate_funds'],
            ['ticker' => 'MFII11', 'name' => 'Mérito Desenvolvimento Imobiliário I', 'price' => '101', 'type' => 'real_estate_funds'],
            ['ticker' => 'ANCR11', 'name' => 'Ancar IC', 'price' => '101', 'type' => 'real_estate_funds'],
            ['ticker' => 'VVRI11', 'name' => 'V2 Renda Imobiliária', 'price' => '101', 'type' => 'real_estate_funds'],
            ['ticker' => 'MGIM11', 'name' => 'Mogno Real Estate Impact Development', 'price' => '101.1', 'type' => 'real_estate_funds'],
            ['ticker' => 'VGII11', 'name' => 'Valora CRI Infra II', 'price' => '101.41', 'type' => 'real_estate_funds'],
            ['ticker' => 'VVPR11', 'name' => 'V2 Properties', 'price' => '101.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'BLCA11', 'name' => 'Catuaí VBI Triple A', 'price' => '101.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'YEES11', 'name' => 'Hedge Yees', 'price' => '102.05', 'type' => 'real_estate_funds'],
            ['ticker' => 'TVRI11', 'name' => 'Tivio Renda Imobiliária', 'price' => '102.12', 'type' => 'real_estate_funds'],
            ['ticker' => 'KORE11', 'name' => 'Kinea Oportunidades Real Estate', 'price' => '102.29', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTLG11', 'name' => 'BTG Pactual Logística', 'price' => '102.39', 'type' => 'real_estate_funds'],
            ['ticker' => 'VANG11', 'name' => 'Icatu Vanguarda', 'price' => '102.45', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPLG11', 'name' => 'XP Log', 'price' => '102.76', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGCR11', 'name' => 'Pátria Recebiveis Imobiliários', 'price' => '103.04', 'type' => 'real_estate_funds'],
            ['ticker' => 'SNID11', 'name' => 'Suno Infra', 'price' => '103.3', 'type' => 'real_estate_funds'],
            ['ticker' => 'BCIA11', 'name' => 'Bradesco Carteira Imobiliária Ativa', 'price' => '103.35', 'type' => 'real_estate_funds'],
            ['ticker' => 'MTOF11', 'name' => 'Alianza Multioffices', 'price' => '103.37', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNCA11', 'name' => 'Kinea Crédito Agro Fiagro', 'price' => '103.39', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNCR11', 'name' => 'Kinea Rendimentos Imobiliários FII', 'price' => '103.86', 'type' => 'real_estate_funds'],
            ['ticker' => 'URHF11', 'name' => 'Urca Hedge Fund', 'price' => '104', 'type' => 'real_estate_funds'],
            ['ticker' => 'CRAA11', 'name' => 'Sparta Fiagro', 'price' => '104', 'type' => 'real_estate_funds'],
            ['ticker' => 'NUIF11', 'name' => 'Nu FI-Infra', 'price' => '104.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'FZDA11', 'name' => '051 Agro Fiagro', 'price' => '104.04', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNUQ11', 'name' => 'Kinea Unique HY CDI', 'price' => '104.29', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNOX11', 'name' => 'Knox Debt FIP-IE', 'price' => '104.55', 'type' => 'real_estate_funds'],
            ['ticker' => 'CACR11', 'name' => 'Cartesia Recebíveis Imobiliários', 'price' => '104.79', 'type' => 'real_estate_funds'],
            ['ticker' => 'TRNT11', 'name' => 'Torre Norte', 'price' => '105', 'type' => 'real_estate_funds'],
            ['ticker' => 'BREV11', 'name' => 'Brazil Real Estate Victory Fund I', 'price' => '105', 'type' => 'real_estate_funds'],
            ['ticker' => 'IFRI11', 'name' => 'Itaú FIC FI INFRA CDI', 'price' => '105', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBVA11', 'name' => 'Rio Bravo Renda Varejo', 'price' => '105.14', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTSI11', 'name' => 'BTSP II', 'price' => '105.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNHY11', 'name' => 'Kinea High Yield CRI', 'price' => '105.77', 'type' => 'real_estate_funds'],
            ['ticker' => 'TRXF11', 'name' => 'TRX Real Estate', 'price' => '105.91', 'type' => 'real_estate_funds'],
            ['ticker' => 'PNRC11', 'name' => 'Panorama Real Estate Crédito', 'price' => '106.36', 'type' => 'real_estate_funds'],
            ['ticker' => 'SAAG11', 'name' => 'Santander Agências', 'price' => '106.61', 'type' => 'real_estate_funds'],
            ['ticker' => 'BPRP11', 'name' => 'BRLPROP', 'price' => '106.94', 'type' => 'real_estate_funds'],
            ['ticker' => 'JURO11', 'name' => 'Sparta Infra FIC', 'price' => '107.61', 'type' => 'real_estate_funds'],
            ['ticker' => 'MALL11', 'name' => 'Genial Malls', 'price' => '107.75', 'type' => 'real_estate_funds'],
            ['ticker' => 'ALZR11', 'name' => 'Alianza Trust Renda Imobiliária', 'price' => '108.21', 'type' => 'real_estate_funds'],
            ['ticker' => 'BRZP11', 'name' => 'BRZ Infra Portos FIP-IE', 'price' => '108.49', 'type' => 'real_estate_funds'],
            ['ticker' => 'CPOF11', 'name' => 'Capitânia Office', 'price' => '108.5', 'type' => 'real_estate_funds'],
            ['ticker' => 'RINV11', 'name' => 'Real Investor FII', 'price' => '109.54', 'type' => 'real_estate_funds'],
            ['ticker' => 'ENDD11', 'name' => 'Endurance Debt FIP-IE', 'price' => '109.7', 'type' => 'real_estate_funds'],
            ['ticker' => 'MCEM11', 'name' => 'Mérito Cemitérios', 'price' => '109.96', 'type' => 'real_estate_funds'],
            ['ticker' => 'NVRP11', 'name' => 'Nova Raposo Multiestratégia FIP-IE', 'price' => '110', 'type' => 'real_estate_funds'],
            ['ticker' => 'FZDB11', 'name' => '051 Agro Fazendas III', 'price' => '110', 'type' => 'real_estate_funds'],
            ['ticker' => 'IFRA11', 'name' => 'Itaú FIC FI-Infra', 'price' => '110.09', 'type' => 'real_estate_funds'],
            ['ticker' => 'MMPD11', 'name' => 'Mauá Capital MPD Desenvolvimento Residencial', 'price' => '110.61', 'type' => 'real_estate_funds'],
            ['ticker' => 'HDEL11', 'name' => 'Hedge Desenvolvimento Logístico', 'price' => '111', 'type' => 'real_estate_funds'],
            ['ticker' => 'NEXG11', 'name' => 'NEX Crédito Agro', 'price' => '111', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTML11', 'name' => 'Barra Malls', 'price' => '111.28', 'type' => 'real_estate_funds'],
            ['ticker' => 'ZAVI11', 'name' => 'Zavit Real Estate Fund', 'price' => '111.65', 'type' => 'real_estate_funds'],
            ['ticker' => 'HUSC11', 'name' => 'Hospital Unimed Sul Capixaba', 'price' => '112', 'type' => 'real_estate_funds'],
            ['ticker' => 'LVBI11', 'name' => 'VBI Logístico', 'price' => '112.67', 'type' => 'real_estate_funds'],
            ['ticker' => 'VISC11', 'name' => 'Vinci Shopping Centers', 'price' => '112.87', 'type' => 'real_estate_funds'],
            ['ticker' => 'LASC11', 'name' => 'Legatus Shoppings', 'price' => '112.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPML11', 'name' => 'XP Malls', 'price' => '112.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'NEWL11', 'name' => 'Newport Logística', 'price' => '114.92', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGRE11', 'name' => 'Pátria Escritórios', 'price' => '115.07', 'type' => 'real_estate_funds'],
            ['ticker' => 'BBRC11', 'name' => 'BB Renda Corporativa', 'price' => '115.49', 'type' => 'real_estate_funds'],
            ['ticker' => 'JASC11', 'name' => 'Jasc Renda Varejo FII', 'price' => '115.77', 'type' => 'real_estate_funds'],
            ['ticker' => 'CDII11', 'name' => 'Sparta Infra CDI', 'price' => '116.15', 'type' => 'real_estate_funds'],
            ['ticker' => 'FCFL11', 'name' => 'Campus Faria Lima', 'price' => '116.4', 'type' => 'real_estate_funds'],
            ['ticker' => 'BRCO11', 'name' => 'Bresco Logística', 'price' => '116.89', 'type' => 'real_estate_funds'],
            ['ticker' => 'TGAR11', 'name' => 'TG Ativo Real', 'price' => '117.47', 'type' => 'real_estate_funds'],
            ['ticker' => 'BNFS11', 'name' => 'Banrisul Novas Fronteiras', 'price' => '120.13', 'type' => 'real_estate_funds'],
            ['ticker' => 'XPHT11', 'name' => 'XP Hotéis (Cota Sênior)', 'price' => '123', 'type' => 'real_estate_funds'],
            ['ticker' => 'BDIV11', 'name' => 'BTG Pactual Infrastrutura Dividendos FIP-IE', 'price' => '123', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTWR11', 'name' => 'BTowers', 'price' => '125', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGRU11', 'name' => 'Pátria Renda Urbana', 'price' => '127.28', 'type' => 'real_estate_funds'],
            ['ticker' => 'ERPA11', 'name' => 'Europa 105', 'price' => '134', 'type' => 'real_estate_funds'],
            ['ticker' => 'RCRB11', 'name' => 'Rio Bravo Renda Corporativa', 'price' => '134', 'type' => 'real_estate_funds'],
            ['ticker' => 'HBCR11', 'name' => 'HBC Renda Urbana', 'price' => '135', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBED11', 'name' => 'Rio Bravo Renda Educacional', 'price' => '136.2', 'type' => 'real_estate_funds'],
            ['ticker' => 'KDIF11', 'name' => 'Kinea FI-Infra', 'price' => '137', 'type' => 'real_estate_funds'],
            ['ticker' => 'FLMA11', 'name' => 'Continental Square Faria Lima', 'price' => '141.42', 'type' => 'real_estate_funds'],
            ['ticker' => 'SPMO11', 'name' => 'Supremo FII', 'price' => '144', 'type' => 'real_estate_funds'],
            ['ticker' => 'JCCJ11', 'name' => 'JHSF Capital Cidade Jardim', 'price' => '145', 'type' => 'real_estate_funds'],
            ['ticker' => 'TCIN11', 'name' => 'G5 Cidade Nova', 'price' => '145.92', 'type' => 'real_estate_funds'],
            ['ticker' => 'HRES11', 'name' => 'Hire Residencial I', 'price' => '149.25', 'type' => 'real_estate_funds'],
            ['ticker' => 'TRXB11', 'name' => 'TRX Real Estate II', 'price' => '149.44', 'type' => 'real_estate_funds'],
            ['ticker' => 'BRLA11', 'name' => 'BRL Prop II', 'price' => '150.03', 'type' => 'real_estate_funds'],
            ['ticker' => 'JCIN11', 'name' => 'FOF JHSF Capital Institucional', 'price' => '150.66', 'type' => 'real_estate_funds'],
            ['ticker' => 'FAED11', 'name' => 'Anhanguera Educacional', 'price' => '150.77', 'type' => 'real_estate_funds'],
            ['ticker' => 'JPPC11', 'name' => 'JPP Capital', 'price' => '151.02', 'type' => 'real_estate_funds'],
            ['ticker' => 'REIT11', 'name' => 'Singulare FII', 'price' => '155.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'KNRI11', 'name' => 'Kinea Renda Imobiliária', 'price' => '155.98', 'type' => 'real_estate_funds'],
            ['ticker' => 'BTSG11', 'name' => 'BTSP I', 'price' => '160', 'type' => 'real_estate_funds'],
            ['ticker' => 'MMVE11', 'name' => 'Maresias', 'price' => '161.87', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGLG11', 'name' => 'Pátria Log', 'price' => '161.88', 'type' => 'real_estate_funds'],
            ['ticker' => 'STRX11', 'name' => 'StarX', 'price' => '168', 'type' => 'real_estate_funds'],
            ['ticker' => 'FIIP11B', 'name' => 'RB Capital Renda I', 'price' => '171.1', 'type' => 'real_estate_funds'],
            ['ticker' => 'EDFO11', 'name' => 'Edifício Ourinvest', 'price' => '179.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'HTMX11', 'name' => 'Hotel Maxinvest', 'price' => '180.51', 'type' => 'real_estate_funds'],
            ['ticker' => 'NSLU11', 'name' => 'Hospital Nossa Senhora de Lourdes', 'price' => '182', 'type' => 'real_estate_funds'],
            ['ticker' => 'FISD11', 'name' => 'São Domingos', 'price' => '188.4', 'type' => 'real_estate_funds'],
            ['ticker' => 'FPNG11', 'name' => 'Pedra Negra Renda Imobiliária', 'price' => '200', 'type' => 'real_estate_funds'],
            ['ticker' => 'ONEF11', 'name' => 'The One', 'price' => '200.03', 'type' => 'real_estate_funds'],
            ['ticker' => 'HILG11', 'name' => 'Hire Log I', 'price' => '203.55', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGBS11', 'name' => 'Hedge Brasil Shopping', 'price' => '213.3', 'type' => 'real_estate_funds'],
            ['ticker' => 'CXTL11', 'name' => 'Caixa Seq Logística Renda', 'price' => '224.88', 'type' => 'real_estate_funds'],
            ['ticker' => 'FPAB11', 'name' => 'Projeto Água Branca', 'price' => '226.68', 'type' => 'real_estate_funds'],
            ['ticker' => 'RZEO11', 'name' => 'Riza Eos Fiagro', 'price' => '242.54', 'type' => 'real_estate_funds'],
            ['ticker' => 'EURO11', 'name' => 'Europar', 'price' => '244.88', 'type' => 'real_estate_funds'],
            ['ticker' => 'TJKB11', 'name' => 'Tjk Renda Imobiliária', 'price' => '270', 'type' => 'real_estate_funds'],
            ['ticker' => 'HCRI11', 'name' => 'Hospital da Criança', 'price' => '285', 'type' => 'real_estate_funds'],
            ['ticker' => 'HGPO11', 'name' => 'Pátria Prime Offices', 'price' => '301.86', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBOP11', 'name' => 'Rio Bravo Oportunidades Imobiliárias', 'price' => '366.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'VERE11', 'name' => 'Vereda', 'price' => '445.76', 'type' => 'real_estate_funds'],
            ['ticker' => 'LPLP11', 'name' => 'Lago da Pedra', 'price' => '500', 'type' => 'real_estate_funds'],
            ['ticker' => 'FIIB11', 'name' => 'Industrial do Brasil', 'price' => '504.03', 'type' => 'real_estate_funds'],
            ['ticker' => 'MYDW11', 'name' => 'Riza Meyenii', 'price' => '550.16', 'type' => 'real_estate_funds'],
            ['ticker' => 'FAMB11B', 'name' => 'Edifício Almirante Barroso', 'price' => '609.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'BBFI11', 'name' => 'BB Progressivo', 'price' => '626.87', 'type' => 'real_estate_funds'],
            ['ticker' => 'ALMI11', 'name' => 'Torre Almirante', 'price' => '630', 'type' => 'real_estate_funds'],
            ['ticker' => 'CFHI11', 'name' => 'CF2 FII', 'price' => '650', 'type' => 'real_estate_funds'],
            ['ticker' => 'DOVL11', 'name' => 'Dovel', 'price' => '666.3', 'type' => 'real_estate_funds'],
            ['ticker' => 'VXXV11', 'name' => 'Genesis Multiestratégia', 'price' => '673', 'type' => 'real_estate_funds'],
            ['ticker' => 'ELDO11', 'name' => 'Eldorado', 'price' => '683.36', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBTS11', 'name' => 'RB Capital TFO Situs', 'price' => '725', 'type' => 'real_estate_funds'],
            ['ticker' => 'ROOF11', 'name' => 'Rooftop I', 'price' => '727.2', 'type' => 'real_estate_funds'],
            ['ticker' => 'ZIFI11', 'name' => 'Zion Capital', 'price' => '765', 'type' => 'real_estate_funds'],
            ['ticker' => 'SHPH11', 'name' => 'Shopping Pátio Higienópolis', 'price' => '888', 'type' => 'real_estate_funds'],
            ['ticker' => 'PBLV11', 'name' => 'Prologis Brazil Logistics Venture', 'price' => '900.59', 'type' => 'real_estate_funds'],
            ['ticker' => 'BICE11', 'name' => 'Brio Crédito Estruturado', 'price' => '920', 'type' => 'real_estate_funds'],
            ['ticker' => 'BRIP11', 'name' => 'Brio Real Estate III', 'price' => '969.99', 'type' => 'real_estate_funds'],
            ['ticker' => 'BIPD11', 'name' => 'Brio Real Estate IV', 'price' => '988.17', 'type' => 'real_estate_funds'],
            ['ticker' => 'LKDV11', 'name' => 'Development V1', 'price' => '997.23', 'type' => 'real_estate_funds'],
            ['ticker' => 'CFII11', 'name' => 'CF3 FII', 'price' => '1000', 'type' => 'real_estate_funds'],
            ['ticker' => 'BRIM11', 'name' => 'Brio Real Estate II', 'price' => '1008', 'type' => 'real_estate_funds'],
            ['ticker' => 'EGDB11', 'name' => 'Desenvolvimento de Escritórios Boutique', 'price' => '1015', 'type' => 'real_estate_funds'],
            ['ticker' => 'KOPA11', 'name' => 'Kinea Oportunidades Agro I', 'price' => '1016.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'SOLR11', 'name' => 'Solarium', 'price' => '1051', 'type' => 'real_estate_funds'],
            ['ticker' => 'HBTT11', 'name' => 'Habitat I', 'price' => '1055.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'SHDP11B', 'name' => 'Shopping Parque Dom Pedro', 'price' => '1094.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'RSPD11', 'name' => 'RB Capital Desenvolvimento Residencial III', 'price' => '1099.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'KEVE11', 'name' => 'Even II', 'price' => '1137', 'type' => 'real_estate_funds'],
            ['ticker' => 'PNDL11', 'name' => 'Panorama Desenvolvimento Logístico', 'price' => '1190', 'type' => 'real_estate_funds'],
            ['ticker' => 'OBAL11', 'name' => 'Opportunity Balassiano FII', 'price' => '1213.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'HUSI11', 'name' => 'HUSI', 'price' => '1225.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'SPDE11', 'name' => 'WHG Finvest SP Realty', 'price' => '1238', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRI11', 'name' => 'RBR Desenvolvimento III', 'price' => '1275.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'GESE11B', 'name' => 'General Severiano', 'price' => '1372.12', 'type' => 'real_estate_funds'],
            ['ticker' => 'BVAR11', 'name' => 'Brasil Varejo', 'price' => '1390.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'AATH11', 'name' => 'Athon Energia ESG I FIP-IE', 'price' => '1399', 'type' => 'real_estate_funds'],
            ['ticker' => 'BRIX11', 'name' => 'Brix FII', 'price' => '1673', 'type' => 'real_estate_funds'],
            ['ticker' => 'PQDP11', 'name' => 'Parque Dom Pedro Shopping Center', 'price' => '1900', 'type' => 'real_estate_funds'],
            ['ticker' => 'FLRP11', 'name' => 'Hedge Floripa Shopping', 'price' => '2060', 'type' => 'real_estate_funds'],
            ['ticker' => 'FTCE11', 'name' => 'Opportunity', 'price' => '2856', 'type' => 'real_estate_funds'],
            ['ticker' => 'IFIX', 'name' => 'IFIX Índice de Fundos Imobiliários', 'price' => '3371.83', 'type' => 'real_estate_funds'],
            ['ticker' => 'ASRF11', 'name' => 'Asa Retrofits I', 'price' => '10882.00', 'type' => 'real_estate_funds'],
            ['ticker' => 'RBRM11', 'name' => 'RBR Desenvolvimento', 'price' => '16565.01', 'type' => 'real_estate_funds'],
            ['ticker' => 'ERCR11', 'name' => 'Estoque Residencial e Comercial Rio de Janeiro', 'price' => '72991.40', 'type' => 'real_estate_funds']
        ];

        foreach ($funds as $fund) {
            $f = app(Active::class)->firstOrNew(
                $fund
            );

            $f->save();
        }
    }
}
